from __future__ import annotations

# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from enum import Enum
from typing import Final

from openmac._internal.sdef import meta as sdef_meta


class Edfm(str, Enum):
    """Generated from SDEF."""

    MAC_OS_FORMAT = "dfhf"
    MAC_OS_EXTENDED_FORMAT = "dfh+"
    UFS_FORMAT = "dfuf"
    NFS_FORMAT = "dfnf"
    AUDIO_FORMAT = "dfau"
    PRO_DOS_FORMAT = "dfpr"
    MSDOS_FORMAT = "dfms"
    NTFS_FORMAT = "dfnt"
    ISO_9660_FORMAT = "df96"
    HIGH_SIERRA_FORMAT = "dfhs"
    QUICK_TAKE_FORMAT = "dfqt"
    APPLE_PHOTO_FORMAT = "dfph"
    APPLE_SHARE_FORMAT = "dfas"
    UDF_FORMAT = "dfud"
    WEB_DAV_FORMAT = "dfwd"
    FTP_FORMAT = "dfft"
    PACKET_WRITTEN_UDF_FORMAT = "dfpu"
    XSAN_FORMAT = "dfac"
    APFS_FORMAT = "dfap"
    EX_FAT_FORMAT = "dfxf"
    SMB_FORMAT = "dfsm"
    UNKNOWN_FORMAT = "df??"


EDFM_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="edfm",
    code="edfm",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="Mac OS format", code="dfhf", description=None),
        sdef_meta.EnumeratorMeta(name="Mac OS Extended format", code="dfh+", description=None),
        sdef_meta.EnumeratorMeta(name="UFS format", code="dfuf", description=None),
        sdef_meta.EnumeratorMeta(name="NFS format", code="dfnf", description=None),
        sdef_meta.EnumeratorMeta(name="audio format", code="dfau", description=None),
        sdef_meta.EnumeratorMeta(name="ProDOS format", code="dfpr", description=None),
        sdef_meta.EnumeratorMeta(name="MSDOS format", code="dfms", description=None),
        sdef_meta.EnumeratorMeta(name="NTFS format", code="dfnt", description=None),
        sdef_meta.EnumeratorMeta(name="ISO 9660 format", code="df96", description=None),
        sdef_meta.EnumeratorMeta(name="High Sierra format", code="dfhs", description=None),
        sdef_meta.EnumeratorMeta(name="QuickTake format", code="dfqt", description=None),
        sdef_meta.EnumeratorMeta(name="Apple Photo format", code="dfph", description=None),
        sdef_meta.EnumeratorMeta(name="AppleShare format", code="dfas", description=None),
        sdef_meta.EnumeratorMeta(name="UDF format", code="dfud", description=None),
        sdef_meta.EnumeratorMeta(name="WebDAV format", code="dfwd", description=None),
        sdef_meta.EnumeratorMeta(name="FTP format", code="dfft", description=None),
        sdef_meta.EnumeratorMeta(name="Packet written UDF format", code="dfpu", description=None),
        sdef_meta.EnumeratorMeta(name="Xsan format", code="dfac", description=None),
        sdef_meta.EnumeratorMeta(name="APFS format", code="dfap", description=None),
        sdef_meta.EnumeratorMeta(name="ExFAT format", code="dfxf", description=None),
        sdef_meta.EnumeratorMeta(name="SMB format", code="dfsm", description=None),
        sdef_meta.EnumeratorMeta(name="unknown format", code="df??", description=None),
    ),
)
