from __future__ import annotations

import importlib

# ruff: noqa: D301, D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import TYPE_CHECKING, ClassVar

from pydantic import Field

import openmac._internal.sdef.types as sdef_types
from openmac._internal.sdef import meta as sdef_meta
from openmac._internal.sdef.base import SDEFClass

if TYPE_CHECKING:
    from openmac.apps.chrome.sdef.suites.chromium.classes import Tab as ChromiumTabType


class Application(SDEFClass):
    """The application\'s top-level scripting object.\n\nSDEF extras: {"cocoas": [{"class": "BrowserCrApplication"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="application",
        code="capp",
        description="The application's top-level scripting object.",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="name",
                code="pnam",
                type="text",
                description="The name of the application.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="frontmost",
                code="pisf",
                type="boolean",
                description="Is this the frontmost (active) application?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="version",
                code="vers",
                type="text",
                description="The version of the application.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(
                type="window",
                description="The windows contained within this application, ordered front to back.",
                hidden=None,
                access=None,
            ),
        ),
        responds_to=(
            (
                "open",
                None,
            ),
            (
                "print",
                None,
            ),
            (
                "quit",
                None,
            ),
        ),
    )
    name: str = Field(..., alias="name", description="The name of the application.")
    frontmost: bool = Field(
        ...,
        alias="frontmost",
        description="Is this the frontmost (active) application?",
        json_schema_extra={"cocoas": [{"key": "isActive"}]},
    )
    version: str = Field(..., alias="version", description="The version of the application.")


class Window(SDEFClass):
    """A window.\n\nSDEF extras: {"cocoas": [{"class": "WindowAppleScript"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="window",
        code="cwin",
        description="A window.",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="given name",
                code="GNam",
                type="text",
                description="The given name of the window.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="name",
                code="pnam",
                type="text",
                description="The full title of the window.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="id",
                code="ID  ",
                type="text",
                description="The unique identifier of the window.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="index",
                code="pidx",
                type="integer",
                description="The index of the window, ordered front to back.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="bounds",
                code="pbnd",
                type="rectangle",
                description="The bounding rectangle of the window.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="closeable",
                code="hclb",
                type="boolean",
                description="Whether the window has a close box.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="minimizable",
                code="ismn",
                type="boolean",
                description="Whether the window can be minimized.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="minimized",
                code="pmnd",
                type="boolean",
                description="Whether the window is currently minimized.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="resizable",
                code="prsz",
                type="boolean",
                description="Whether the window can be resized.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="visible",
                code="pvis",
                type="boolean",
                description="Whether the window is currently visible.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="zoomable",
                code="iszm",
                type="boolean",
                description="Whether the window can be zoomed.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="zoomed",
                code="pzum",
                type="boolean",
                description="Whether the window is currently zoomed.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="active tab",
                code="acTa",
                type="tab",
                description="Returns the currently selected tab",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="mode",
                code="mode",
                type="text",
                description="Represents the mode of the window which can be 'normal' or 'incognito', can be set only once during creation of the window.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="active tab index",
                code="acTI",
                type="integer",
                description="The index of the active tab.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(
                type="tab",
                description="The tabs contained within the window.",
                hidden=None,
                access=None,
            ),
        ),
        responds_to=(
            (
                "close",
                None,
            ),
        ),
    )
    given_name: str = Field(
        ...,
        alias="given name",
        description="The given name of the window.",
        json_schema_extra={"cocoas": [{"key": "givenName"}]},
    )
    name: str = Field(
        ...,
        alias="name",
        description="The full title of the window.",
        json_schema_extra={"cocoas": [{"key": "title"}]},
    )
    id_: str = Field(
        ...,
        alias="id",
        description="The unique identifier of the window.",
        json_schema_extra={"cocoas": [{"key": "uniqueID"}]},
    )
    index: int = Field(
        ...,
        alias="index",
        description="The index of the window, ordered front to back.",
        json_schema_extra={"cocoas": [{"key": "orderedIndex"}]},
    )
    bounds: sdef_types.Rectangle = Field(
        ...,
        alias="bounds",
        description="The bounding rectangle of the window.",
        json_schema_extra={"cocoas": [{"key": "boundsAsQDRect"}]},
    )
    closeable: bool = Field(
        ...,
        alias="closeable",
        description="Whether the window has a close box.",
        json_schema_extra={"cocoas": [{"key": "hasCloseBox"}]},
    )
    minimizable: bool = Field(
        ...,
        alias="minimizable",
        description="Whether the window can be minimized.",
        json_schema_extra={"cocoas": [{"key": "isMiniaturizable"}]},
    )
    minimized: bool = Field(
        ...,
        alias="minimized",
        description="Whether the window is currently minimized.",
        json_schema_extra={"cocoas": [{"key": "isMiniaturized"}]},
    )
    resizable: bool = Field(
        ...,
        alias="resizable",
        description="Whether the window can be resized.",
        json_schema_extra={"cocoas": [{"key": "isResizable"}]},
    )
    visible: bool = Field(
        ...,
        alias="visible",
        description="Whether the window is currently visible.",
        json_schema_extra={"cocoas": [{"key": "isVisible"}]},
    )
    zoomable: bool = Field(
        ...,
        alias="zoomable",
        description="Whether the window can be zoomed.",
        json_schema_extra={"cocoas": [{"key": "isZoomable"}]},
    )
    zoomed: bool = Field(
        ...,
        alias="zoomed",
        description="Whether the window is currently zoomed.",
        json_schema_extra={"cocoas": [{"key": "isZoomed"}]},
    )
    active_tab: sdef_types.Specifier[ChromiumTabType] = Field(
        ...,
        alias="active tab",
        description="Returns the currently selected tab",
        json_schema_extra={"cocoas": [{"key": "activeTab"}]},
    )
    mode: str = Field(
        ...,
        alias="mode",
        description="Represents the mode of the window which can be 'normal' or 'incognito', can be set only once during creation of the window.",
        json_schema_extra={"cocoas": [{"key": "mode"}]},
    )
    active_tab_index: int = Field(
        ...,
        alias="active tab index",
        description="The index of the active tab.",
    )


_CROSS_SUITE_TYPES_NAMESPACE = {
    "ChromiumTabType": importlib.import_module(
        "openmac.apps.chrome.sdef.suites.chromium.classes",
    ).Tab,
}

Application.model_rebuild(_types_namespace=_CROSS_SUITE_TYPES_NAMESPACE)
Window.model_rebuild(_types_namespace=_CROSS_SUITE_TYPES_NAMESPACE)
