from __future__ import annotations

# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from enum import Enum
from typing import Final

from openmac._internal.sdef import meta as sdef_meta


class Earr(str, Enum):
    """Generated from SDEF."""

    NOT_ARRANGED = "narr"
    SNAP_TO_GRID = "grda"
    ARRANGED_BY_NAME = "nama"
    ARRANGED_BY_MODIFICATION_DATE = "mdta"
    ARRANGED_BY_CREATION_DATE = "cdta"
    ARRANGED_BY_SIZE = "siza"
    ARRANGED_BY_KIND = "kina"
    ARRANGED_BY_LABEL = "laba"


EARR_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="earr",
    code="earr",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="not arranged", code="narr", description=None),
        sdef_meta.EnumeratorMeta(name="snap to grid", code="grda", description=None),
        sdef_meta.EnumeratorMeta(name="arranged by name", code="nama", description=None),
        sdef_meta.EnumeratorMeta(
            name="arranged by modification date",
            code="mdta",
            description=None,
        ),
        sdef_meta.EnumeratorMeta(name="arranged by creation date", code="cdta", description=None),
        sdef_meta.EnumeratorMeta(name="arranged by size", code="siza", description=None),
        sdef_meta.EnumeratorMeta(name="arranged by kind", code="kina", description=None),
        sdef_meta.EnumeratorMeta(name="arranged by label", code="laba", description=None),
    ),
)


class Epos(str, Enum):
    """Generated from SDEF."""

    RIGHT = "lrgt"
    BOTTOM = "lbot"


EPOS_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="epos",
    code="epos",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="right", code="lrgt", description=None),
        sdef_meta.EnumeratorMeta(name="bottom", code="lbot", description=None),
    ),
)


class Sodr(str, Enum):
    """Generated from SDEF."""

    NORMAL = "snrm"
    REVERSED = "srvs"


SODR_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="sodr",
    code="sodr",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="normal", code="snrm", description=None),
        sdef_meta.EnumeratorMeta(name="reversed", code="srvs", description=None),
    ),
)


class Elsv(str, Enum):
    """Generated from SDEF."""

    NAME_COLUMN = "elsn"
    MODIFICATION_DATE_COLUMN = "elsm"
    CREATION_DATE_COLUMN = "elsc"
    SIZE_COLUMN = "elss"
    KIND_COLUMN = "elsk"
    LABEL_COLUMN = "elsl"
    VERSION_COLUMN = "elsv"
    COMMENT_COLUMN = "elsC"


ELSV_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="elsv",
    code="elsv",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="name column", code="elsn", description=None),
        sdef_meta.EnumeratorMeta(name="modification date column", code="elsm", description=None),
        sdef_meta.EnumeratorMeta(name="creation date column", code="elsc", description=None),
        sdef_meta.EnumeratorMeta(name="size column", code="elss", description=None),
        sdef_meta.EnumeratorMeta(name="kind column", code="elsk", description=None),
        sdef_meta.EnumeratorMeta(name="label column", code="elsl", description=None),
        sdef_meta.EnumeratorMeta(name="version column", code="elsv", description=None),
        sdef_meta.EnumeratorMeta(name="comment column", code="elsC", description=None),
    ),
)


class Lvic(str, Enum):
    """Generated from SDEF."""

    SMALL_ICON = "smic"
    LARGE_ICON = "lgic"


LVIC_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="lvic",
    code="lvic",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="small icon", code="smic", description=None),
        sdef_meta.EnumeratorMeta(name="large icon", code="lgic", description=None),
    ),
)
