from __future__ import annotations

# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import Final

from openmac._internal.sdef import meta as sdef_meta

SUITE_META: Final[sdef_meta.SuiteMeta] = sdef_meta.SuiteMeta(
    name="Finder Basics",
    code="fndr",
    description="Commonly-used Finder commands and object classes",
    hidden=None,
)
