from __future__ import annotations

# ruff: noqa: D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar

from openmac._internal.sdef import meta as sdef_meta
from openmac._internal.sdef.base import SDEFCommand


class RestartCommand(SDEFCommand):
    """Restart the computer"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="restart",
        code="fndrrest",
        description="Restart the computer",
        hidden=None,
        bundle_id="com.apple.finder",
        direct_parameter_type=None,
        parameters=(),
        results=(),
        access_groups=(),
    )


class ShutDownCommand(SDEFCommand):
    """Shut Down the computer"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="shut down",
        code="fndrshut",
        description="Shut Down the computer",
        hidden=None,
        bundle_id="com.apple.finder",
        direct_parameter_type=None,
        parameters=(),
        results=(),
        access_groups=(),
    )


class SleepCommand(SDEFCommand):
    """Put the computer to sleep"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="sleep",
        code="fndrslep",
        description="Put the computer to sleep",
        hidden=None,
        bundle_id="com.apple.finder",
        direct_parameter_type=None,
        parameters=(),
        results=(),
        access_groups=(),
    )
