from __future__ import annotations

from openmac.chrome.suites.chromium_suite import ChromiumSuite

# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from openmac.chrome.suites.standard_suite import StandardSuite

__all__ = ["ChromiumSuite", "StandardSuite"]
