from __future__ import annotations

# ruff: noqa: D301, D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar, Final

from pydantic import Field

import openmac._internal.sdef as sdef_types
import openmac.chrome.suites.standard_suite as standard_suite_module
from openmac._internal import sdef_meta
from openmac._internal.models import SDEFModel

SUITE_META: Final[sdef_meta.SuiteMeta] = sdef_meta.SuiteMeta(
    name="Chromium Suite",
    code="CrSu",
    description="Common classes and commands for Chrome.",
    hidden=None,
)


class Tab(SDEFModel):
    """A tab.\n\nSDEF extras: {"cocoas": [{"class": "TabAppleScript"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="tab",
        code="CrTb",
        description="A tab.",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="id",
                code="ID  ",
                type="text",
                description="Unique ID of the tab.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="title",
                code="pnam",
                type="text",
                description="The title of the tab.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="URL",
                code="URL ",
                type="text",
                description="The url visible to the user.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="loading",
                code="ldng",
                type="boolean",
                description="Is loading?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(
            (
                "undo",
                None,
            ),
            (
                "redo",
                None,
            ),
            (
                "cut selection",
                None,
            ),
            (
                "copy selection",
                None,
            ),
            (
                "paste selection",
                None,
            ),
            (
                "select all",
                None,
            ),
            (
                "go back",
                None,
            ),
            (
                "go forward",
                None,
            ),
            (
                "reload",
                None,
            ),
            (
                "stop",
                None,
            ),
            (
                "print",
                None,
            ),
            (
                "view source",
                None,
            ),
            (
                "save",
                None,
            ),
            (
                "close",
                None,
            ),
            (
                "execute",
                None,
            ),
        ),
    )
    id_: str = Field(
        ...,
        alias="id",
        description="Unique ID of the tab.",
        json_schema_extra={"cocoas": [{"key": "uniqueID"}]},
    )
    title: str = Field(..., alias="title", description="The title of the tab.")
    url: str = Field(..., alias="URL", description="The url visible to the user.")
    loading: bool = Field(..., alias="loading", description="Is loading?")


class BookmarkFolder(SDEFModel):
    """A bookmarks folder that contains other bookmarks folder and bookmark items.\n\nSDEF extras: {"cocoas": [{"class": "BookmarkFolderAppleScript"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="bookmark folder",
        code="CrBF",
        description="A bookmarks folder that contains other bookmarks folder and bookmark items.",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="id",
                code="ID  ",
                type="text",
                description="Unique ID of the bookmark folder.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="title",
                code="pnam",
                type="text",
                description="The title of the folder.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="index",
                code="pidx",
                type="number",
                description="Returns the index with respect to its parent bookmark folder.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(
                type="bookmark folder",
                description="The bookmark folders present within.",
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(
                type="bookmark item",
                description="The bookmarks present within.",
                hidden=None,
                access=None,
            ),
        ),
        responds_to=(),
    )
    id_: str = Field(
        ...,
        alias="id",
        description="Unique ID of the bookmark folder.",
        json_schema_extra={"cocoas": [{"key": "uniqueID"}]},
    )
    title: str = Field(..., alias="title", description="The title of the folder.")
    index: float = Field(
        ...,
        alias="index",
        description="Returns the index with respect to its parent bookmark folder.",
        json_schema_extra={"cocoas": [{"key": "index"}]},
    )


class BookmarkItem(SDEFModel):
    """An item consists of an URL and the title of a bookmark\n\nSDEF extras: {"cocoas": [{"class": "BookmarkItemAppleScript"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="bookmark item",
        code="CrBI",
        description="An item consists of an URL and the title of a bookmark",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="id",
                code="ID  ",
                type="text",
                description="Unique ID of the bookmark item.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="title",
                code="pnam",
                type="text",
                description="The title of the bookmark item.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="URL",
                code="URL ",
                type="text",
                description="The URL of the bookmark.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="index",
                code="pidx",
                type="number",
                description="Returns the index with respect to its parent bookmark folder.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    id_: str = Field(
        ...,
        alias="id",
        description="Unique ID of the bookmark item.",
        json_schema_extra={"cocoas": [{"key": "uniqueID"}]},
    )
    title: str = Field(..., alias="title", description="The title of the bookmark item.")
    url: str = Field(..., alias="URL", description="The URL of the bookmark.")
    index: float = Field(
        ...,
        alias="index",
        description="Returns the index with respect to its parent bookmark folder.",
        json_schema_extra={"cocoas": [{"key": "index"}]},
    )


class Application(standard_suite_module.Application):
    """The application\'s top-level scripting object.\n\nSDEF extras: {"cocoas": [{"class": "BrowserCrApplication"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="application",
        code=None,
        description="The application's top-level scripting object.",
        hidden=None,
        inherits="application",
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="bookmarks bar",
                code="ChBB",
                type="bookmark folder",
                description="The bookmarks bar bookmark folder.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="other bookmarks",
                code="ChOB",
                type="bookmark folder",
                description="The other bookmarks bookmark folder.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(
                type="bookmark folder",
                description="Contains the bookmarks bar and other bookmarks folder.",
                hidden=None,
                access="r",
            ),
        ),
        responds_to=(),
    )
    bookmarks_bar: BookmarkFolder = Field(
        ...,
        alias="bookmarks bar",
        description="The bookmarks bar bookmark folder.",
        json_schema_extra={"cocoas": [{"key": "bookmarksBar"}]},
    )
    other_bookmarks: BookmarkFolder = Field(
        ...,
        alias="other bookmarks",
        description="The other bookmarks bookmark folder.",
        json_schema_extra={"cocoas": [{"key": "otherBookmarks"}]},
    )


class ChromiumSuite:
    """Common classes and commands for Chrome."""

    COMMANDS: ClassVar[tuple[sdef_meta.CommandMeta, ...]] = (
        sdef_meta.CommandMeta(
            name="reload",
            code="CrSuRlod",
            description="Reload a tab.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="go back",
            code="CrSuBack",
            description="Go Back (If Possible).",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="go forward",
            code="CrSuFwd ",
            description="Go Forward (If Possible).",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="select all",
            code="CrSuSlAl",
            description="Select all.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="cut selection",
            code="CrSuCut ",
            description="Cut selected text (If Possible).",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="copy selection",
            code="CrSuCop ",
            description="Copy text.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="paste selection",
            code="CrSuPast",
            description="Paste text (If Possible).",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="undo",
            code="CrSuUndo",
            description="Undo the last change.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="redo",
            code="CrSuRedo",
            description="Redo the last change.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="stop",
            code="CrSustop",
            description="Stop the current tab from loading.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="view source",
            code="CrSuVSrc",
            description="View the HTML source of the tab.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="execute",
            code="CrSuExJa",
            description="Execute a piece of javascript.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(
                sdef_meta.ParameterMeta(
                    name="javascript",
                    code="JvSc",
                    type="text",
                    description="The javascript code to execute.",
                    optional=None,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(sdef_meta.ResultMeta(type="any", description=None, optional=None),),
            access_groups=(),
        ),
    )

    def reload(self, direct_parameter: sdef_types.Specifier) -> None:
        """Reload a tab.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def go_back(self, direct_parameter: sdef_types.Specifier) -> None:
        """Go Back (If Possible).\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def go_forward(self, direct_parameter: sdef_types.Specifier) -> None:
        """Go Forward (If Possible).\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def select_all(self, direct_parameter: sdef_types.Specifier) -> None:
        """Select all.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def cut_selection(self, direct_parameter: sdef_types.Specifier) -> None:
        """Cut selected text (If Possible).\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def copy_selection(self, direct_parameter: sdef_types.Specifier) -> None:
        """Copy text.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def paste_selection(self, direct_parameter: sdef_types.Specifier) -> None:
        """Paste text (If Possible).\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def undo(self, direct_parameter: sdef_types.Specifier) -> None:
        """Undo the last change.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def redo(self, direct_parameter: sdef_types.Specifier) -> None:
        """Redo the last change.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def stop(self, direct_parameter: sdef_types.Specifier) -> None:
        """Stop the current tab from loading.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def view_source(self, direct_parameter: sdef_types.Specifier) -> None:
        """View the HTML source of the tab.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def execute(self, direct_parameter: sdef_types.Specifier, *, javascript: str) -> object:
        """Execute a piece of javascript.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [{"key": "javascript"}], "code": "JvSc", "description": "The javascript code to execute.", "name": "javascript", "type": "text", "type_element": []}], "results": [{"type": "any", "type_element": []}]}"""
        raise NotImplementedError


__all__ = ["Application", "BookmarkFolder", "BookmarkItem", "ChromiumSuite", "Tab"]
