from __future__ import annotations

# ruff: noqa: D301, D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar, Final

from pydantic import Field

import openmac._internal.sdef as sdef_types
from openmac._internal import sdef_meta
from openmac._internal.models import SDEFModel

SUITE_META: Final[sdef_meta.SuiteMeta] = sdef_meta.SuiteMeta(
    name="Standard Suite",
    code="core",
    description="Common classes and commands for all applications.",
    hidden=None,
)


class Application(SDEFModel):
    """The application\'s top-level scripting object.\n\nSDEF extras: {"cocoas": [{"class": "BrowserCrApplication"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="application",
        code="capp",
        description="The application's top-level scripting object.",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="name",
                code="pnam",
                type="text",
                description="The name of the application.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="frontmost",
                code="pisf",
                type="boolean",
                description="Is this the frontmost (active) application?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="version",
                code="vers",
                type="text",
                description="The version of the application.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(
                type="window",
                description="The windows contained within this application, ordered front to back.",
                hidden=None,
                access=None,
            ),
        ),
        responds_to=(
            (
                "open",
                None,
            ),
            (
                "print",
                None,
            ),
            (
                "quit",
                None,
            ),
        ),
    )
    name: str = Field(..., alias="name", description="The name of the application.")
    frontmost: bool = Field(
        ...,
        alias="frontmost",
        description="Is this the frontmost (active) application?",
        json_schema_extra={"cocoas": [{"key": "isActive"}]},
    )
    version: str = Field(..., alias="version", description="The version of the application.")


class Window(SDEFModel):
    """A window.\n\nSDEF extras: {"cocoas": [{"class": "WindowAppleScript"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="window",
        code="cwin",
        description="A window.",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="given name",
                code="GNam",
                type="text",
                description="The given name of the window.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="name",
                code="pnam",
                type="text",
                description="The full title of the window.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="id",
                code="ID  ",
                type="text",
                description="The unique identifier of the window.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="index",
                code="pidx",
                type="integer",
                description="The index of the window, ordered front to back.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="bounds",
                code="pbnd",
                type="rectangle",
                description="The bounding rectangle of the window.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="closeable",
                code="hclb",
                type="boolean",
                description="Whether the window has a close box.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="minimizable",
                code="ismn",
                type="boolean",
                description="Whether the window can be minimized.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="minimized",
                code="pmnd",
                type="boolean",
                description="Whether the window is currently minimized.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="resizable",
                code="prsz",
                type="boolean",
                description="Whether the window can be resized.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="visible",
                code="pvis",
                type="boolean",
                description="Whether the window is currently visible.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="zoomable",
                code="iszm",
                type="boolean",
                description="Whether the window can be zoomed.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="zoomed",
                code="pzum",
                type="boolean",
                description="Whether the window is currently zoomed.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="active tab",
                code="acTa",
                type="tab",
                description="Returns the currently selected tab",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="mode",
                code="mode",
                type="text",
                description="Represents the mode of the window which can be 'normal' or 'incognito', can be set only once during creation of the window.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="active tab index",
                code="acTI",
                type="integer",
                description="The index of the active tab.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(
                type="tab",
                description="The tabs contained within the window.",
                hidden=None,
                access=None,
            ),
        ),
        responds_to=(
            (
                "close",
                None,
            ),
        ),
    )
    given_name: str = Field(
        ...,
        alias="given name",
        description="The given name of the window.",
        json_schema_extra={"cocoas": [{"key": "givenName"}]},
    )
    name: str = Field(
        ...,
        alias="name",
        description="The full title of the window.",
        json_schema_extra={"cocoas": [{"key": "title"}]},
    )
    id_: str = Field(
        ...,
        alias="id",
        description="The unique identifier of the window.",
        json_schema_extra={"cocoas": [{"key": "uniqueID"}]},
    )
    index: int = Field(
        ...,
        alias="index",
        description="The index of the window, ordered front to back.",
        json_schema_extra={"cocoas": [{"key": "orderedIndex"}]},
    )
    bounds: sdef_types.Rectangle = Field(
        ...,
        alias="bounds",
        description="The bounding rectangle of the window.",
        json_schema_extra={"cocoas": [{"key": "boundsAsQDRect"}]},
    )
    closeable: bool = Field(
        ...,
        alias="closeable",
        description="Whether the window has a close box.",
        json_schema_extra={"cocoas": [{"key": "hasCloseBox"}]},
    )
    minimizable: bool = Field(
        ...,
        alias="minimizable",
        description="Whether the window can be minimized.",
        json_schema_extra={"cocoas": [{"key": "isMiniaturizable"}]},
    )
    minimized: bool = Field(
        ...,
        alias="minimized",
        description="Whether the window is currently minimized.",
        json_schema_extra={"cocoas": [{"key": "isMiniaturized"}]},
    )
    resizable: bool = Field(
        ...,
        alias="resizable",
        description="Whether the window can be resized.",
        json_schema_extra={"cocoas": [{"key": "isResizable"}]},
    )
    visible: bool = Field(
        ...,
        alias="visible",
        description="Whether the window is currently visible.",
        json_schema_extra={"cocoas": [{"key": "isVisible"}]},
    )
    zoomable: bool = Field(
        ...,
        alias="zoomable",
        description="Whether the window can be zoomed.",
        json_schema_extra={"cocoas": [{"key": "isZoomable"}]},
    )
    zoomed: bool = Field(
        ...,
        alias="zoomed",
        description="Whether the window is currently zoomed.",
        json_schema_extra={"cocoas": [{"key": "isZoomed"}]},
    )
    active_tab: sdef_types.Specifier = Field(
        ...,
        alias="active tab",
        description="Returns the currently selected tab",
        json_schema_extra={"cocoas": [{"key": "activeTab"}]},
    )
    mode: str = Field(
        ...,
        alias="mode",
        description="Represents the mode of the window which can be 'normal' or 'incognito', can be set only once during creation of the window.",
        json_schema_extra={"cocoas": [{"key": "mode"}]},
    )
    active_tab_index: int = Field(
        ...,
        alias="active tab index",
        description="The index of the active tab.",
    )


class StandardSuite:
    """Common classes and commands for all applications."""

    COMMANDS: ClassVar[tuple[sdef_meta.CommandMeta, ...]] = (
        sdef_meta.CommandMeta(
            name="save",
            code="coresave",
            description="Save an object.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(
                sdef_meta.ParameterMeta(
                    name="in",
                    code="kfil",
                    type="file",
                    description="The file in which to save the object.",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="as",
                    code="fltp",
                    type="text",
                    description="The file type in which to save the data. Can be 'only html', 'complete html', or 'single file'; default is 'complete html'.",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(),
            access_groups=(
                (
                    "*",
                    None,
                ),
            ),
        ),
        sdef_meta.CommandMeta(
            name="open",
            code="aevtodoc",
            description="Open a document.",
            hidden=None,
            direct_parameter_type="file",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="close",
            code="coreclos",
            description="Close a window.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(
                (
                    "*",
                    None,
                ),
            ),
        ),
        sdef_meta.CommandMeta(
            name="quit",
            code="aevtquit",
            description="Quit the application.",
            hidden=None,
            direct_parameter_type=None,
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="count",
            code="corecnte",
            description="Return the number of elements of a particular class within an object.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(
                sdef_meta.ParameterMeta(
                    name="each",
                    code="kocl",
                    type="type",
                    description="The class of objects to be counted.",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(
                sdef_meta.ResultMeta(
                    type="integer",
                    description="the number of elements",
                    optional=None,
                ),
            ),
            access_groups=(
                (
                    "*",
                    None,
                ),
            ),
        ),
        sdef_meta.CommandMeta(
            name="delete",
            code="coredelo",
            description="Delete an object.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(
                (
                    "*",
                    None,
                ),
            ),
        ),
        sdef_meta.CommandMeta(
            name="duplicate",
            code="coreclon",
            description="Copy object(s) and put the copies at a new location.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(
                sdef_meta.ParameterMeta(
                    name="to",
                    code="insh",
                    type="location specifier",
                    description="The location for the new object(s).",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="with properties",
                    code="prdt",
                    type="record",
                    description="Properties to be set in the new duplicated object(s).",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(
                sdef_meta.ResultMeta(
                    type="specifier",
                    description="the duplicated object(s)",
                    optional=None,
                ),
            ),
            access_groups=(
                (
                    "*",
                    None,
                ),
            ),
        ),
        sdef_meta.CommandMeta(
            name="exists",
            code="coredoex",
            description="Verify if an object exists.",
            hidden=None,
            direct_parameter_type="any",
            parameters=(),
            results=(
                sdef_meta.ResultMeta(
                    type="boolean",
                    description="true if it exists, false if not",
                    optional=None,
                ),
            ),
            access_groups=(
                (
                    "*",
                    None,
                ),
            ),
        ),
        sdef_meta.CommandMeta(
            name="make",
            code="corecrel",
            description="Make a new object.",
            hidden=None,
            direct_parameter_type=None,
            parameters=(
                sdef_meta.ParameterMeta(
                    name="new",
                    code="kocl",
                    type="type",
                    description="The class of the new object.",
                    optional=None,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="at",
                    code="insh",
                    type="location specifier",
                    description="The location at which to insert the object.",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="with data",
                    code="data",
                    type="any",
                    description="The initial contents of the object.",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="with properties",
                    code="prdt",
                    type="record",
                    description="The initial values for properties of the object.",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(
                sdef_meta.ResultMeta(
                    type="specifier",
                    description="to the new object",
                    optional=None,
                ),
            ),
            access_groups=(
                (
                    "*",
                    None,
                ),
            ),
        ),
        sdef_meta.CommandMeta(
            name="move",
            code="coremove",
            description="Move object(s) to a new location.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(
                sdef_meta.ParameterMeta(
                    name="to",
                    code="insh",
                    type="location specifier",
                    description="The new location for the object(s).",
                    optional=None,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(
                sdef_meta.ResultMeta(
                    type="specifier",
                    description="the moved object(s)",
                    optional=None,
                ),
            ),
            access_groups=(
                (
                    "*",
                    None,
                ),
            ),
        ),
        sdef_meta.CommandMeta(
            name="print",
            code="aevtpdoc",
            description="Print an object.",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
    )

    def save(
        self,
        direct_parameter: sdef_types.Specifier,
        *,
        in_: sdef_types.File | None = None,
        as_: str | None = None,
    ) -> None:
        """Save an object.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the object to save, usually a document or window", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [{"key": "File"}], "code": "kfil", "description": "The file in which to save the object.", "name": "in", "optional": "yes", "type": "file", "type_element": []}, {"cocoa": [{"key": "FileType"}], "code": "fltp", "description": "The file type in which to save the data. Can be \'only html\', \'complete html\', or \'single file\'; default is \'complete html\'.", "name": "as", "optional": "yes", "type": "text", "type_element": []}]}"""
        raise NotImplementedError

    def open_(self, direct_parameter: list[sdef_types.File]) -> None:
        """Open a document.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The file(s) to be opened.", "type_element": [{"list": "yes", "type": "file"}]}]}"""
        raise NotImplementedError

    def close(self, direct_parameter: sdef_types.Specifier) -> None:
        """Close a window.\n\nSDEF extras: {"cocoas": [{"class": "NSCloseCommand"}], "direct_parameters": [{"access_group": [], "description": "the document(s) or window(s) to close.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def quit_(self) -> None:
        """Quit the application.\n\nSDEF extras: {"cocoas": [{"class": "NSQuitCommand"}]}"""
        raise NotImplementedError

    def count(self, direct_parameter: sdef_types.Specifier, *, each: str | None = None) -> int:
        """Return the number of elements of a particular class within an object.\n\nSDEF extras: {"cocoas": [{"class": "NSCountCommand"}], "direct_parameters": [{"access_group": [], "description": "the object whose elements are to be counted", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [{"key": "ObjectClass"}], "code": "kocl", "description": "The class of objects to be counted.", "name": "each", "optional": "yes", "type": "type", "type_element": []}], "results": [{"description": "the number of elements", "type": "integer", "type_element": []}]}"""
        raise NotImplementedError

    def delete(self, direct_parameter: sdef_types.Specifier) -> None:
        """Delete an object.\n\nSDEF extras: {"cocoas": [{"class": "NSDeleteCommand"}], "direct_parameters": [{"access_group": [], "description": "the object to delete", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def duplicate(
        self,
        direct_parameter: sdef_types.Specifier,
        *,
        to: sdef_types.LocationSpecifier | None = None,
        with_properties: sdef_types.Record | None = None,
    ) -> sdef_types.Specifier:
        """Copy object(s) and put the copies at a new location.\n\nSDEF extras: {"cocoas": [{"class": "NSCloneCommand"}], "direct_parameters": [{"access_group": [], "description": "the object(s) to duplicate", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [{"key": "ToLocation"}], "code": "insh", "description": "The location for the new object(s).", "name": "to", "optional": "yes", "type": "location specifier", "type_element": []}, {"cocoa": [{"key": "WithProperties"}], "code": "prdt", "description": "Properties to be set in the new duplicated object(s).", "name": "with properties", "optional": "yes", "type": "record", "type_element": []}], "results": [{"description": "the duplicated object(s)", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def exists(self, direct_parameter: object) -> bool:
        """Verify if an object exists.\n\nSDEF extras: {"cocoas": [{"class": "NSExistsCommand"}], "direct_parameters": [{"access_group": [], "description": "the object in question", "type": "any", "type_element": []}], "results": [{"description": "true if it exists, false if not", "type": "boolean", "type_element": []}]}"""
        raise NotImplementedError

    def make(
        self,
        *,
        new: str,
        at: sdef_types.LocationSpecifier | None = None,
        with_data: object | None = None,
        with_properties: sdef_types.Record | None = None,
    ) -> sdef_types.Specifier:
        """Make a new object.\n\nSDEF extras: {"cocoas": [{"class": "NSCreateCommand"}], "parameters": [{"cocoa": [{"key": "ObjectClass"}], "code": "kocl", "description": "The class of the new object.", "name": "new", "type": "type", "type_element": []}, {"cocoa": [{"key": "Location"}], "code": "insh", "description": "The location at which to insert the object.", "name": "at", "optional": "yes", "type": "location specifier", "type_element": []}, {"cocoa": [{"key": "ObjectData"}], "code": "data", "description": "The initial contents of the object.", "name": "with data", "optional": "yes", "type": "any", "type_element": []}, {"cocoa": [{"key": "KeyDictionary"}], "code": "prdt", "description": "The initial values for properties of the object.", "name": "with properties", "optional": "yes", "type": "record", "type_element": []}], "results": [{"description": "to the new object", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def move(
        self,
        direct_parameter: sdef_types.Specifier,
        *,
        to: sdef_types.LocationSpecifier,
    ) -> sdef_types.Specifier:
        """Move object(s) to a new location.\n\nSDEF extras: {"cocoas": [{"class": "NSMoveCommand"}], "direct_parameters": [{"access_group": [], "description": "the object(s) to move", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [{"key": "ToLocation"}], "code": "insh", "description": "The new location for the object(s).", "name": "to", "type": "location specifier", "type_element": []}], "results": [{"description": "the moved object(s)", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def print_(self, direct_parameter: sdef_types.Specifier) -> None:
        """Print an object.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The file(s) or document(s) to be printed.", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError


__all__ = ["Application", "StandardSuite", "Window"]
