from __future__ import annotations

# ruff: noqa: D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar

from pydantic import Field

import openmac._internal.sdef.types as sdef_types
from openmac._internal.sdef import meta as sdef_meta
from openmac._internal.sdef.base import SDEFClass


class Application(SDEFClass):
    """The Finder"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="application",
        code="capp",
        description="The Finder",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="clipboard",
                code="pcli",
                type="specifier",
                description="(NOT AVAILABLE YET) the Finder's clipboard window",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="name",
                code="pnam",
                type="text",
                description="the Finder's name",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="visible",
                code="pvis",
                type="boolean",
                description="Is the Finder's layer visible?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="frontmost",
                code="pisf",
                type="boolean",
                description="Is the Finder the frontmost process?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="selection",
                code="sele",
                type="specifier",
                description="the selection in the frontmost Finder window",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="insertion location",
                code="pins",
                type="specifier",
                description='the container in which a new folder would appear if "New Folder" was selected',
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="product version",
                code="ver2",
                type="text",
                description="the version of the System software running on this computer",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="version",
                code="vers",
                type="text",
                description="the version of the Finder",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="startup disk",
                code="sdsk",
                type="disk",
                description="the startup disk",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="desktop",
                code="desk",
                type="desktop-object",
                description="the desktop",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="trash",
                code="trsh",
                type="trash-object",
                description="the trash",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="home",
                code="home",
                type="folder",
                description="the home directory",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="computer container",
                code="pcmp",
                type="computer-object",
                description="the computer location (as in Go > Computer)",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="Finder preferences",
                code="pfrp",
                type="preferences",
                description="Various preferences that apply to the Finder as a whole",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(type="item", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="container", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="disk", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="folder", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="alias file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="application file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="document file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="internet location file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="clipping", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="package", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="window", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="Finder window", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="clipping window",
                description=None,
                hidden=None,
                access=None,
            ),
        ),
        responds_to=(),
    )
    clipboard: sdef_types.Specifier = Field(
        ...,
        alias="clipboard",
        description="(NOT AVAILABLE YET) the Finder's clipboard window",
    )
    name: str = Field(..., alias="name", description="the Finder's name")
    visible: bool = Field(..., alias="visible", description="Is the Finder's layer visible?")
    frontmost: bool = Field(
        ...,
        alias="frontmost",
        description="Is the Finder the frontmost process?",
    )
    selection: sdef_types.Specifier = Field(
        ...,
        alias="selection",
        description="the selection in the frontmost Finder window",
    )
    insertion_location: sdef_types.Specifier = Field(
        ...,
        alias="insertion location",
        description='the container in which a new folder would appear if "New Folder" was selected',
    )
    product_version: str = Field(
        ...,
        alias="product version",
        description="the version of the System software running on this computer",
    )
    version: str = Field(..., alias="version", description="the version of the Finder")
    startup_disk: sdef_types.Specifier = Field(
        ...,
        alias="startup disk",
        description="the startup disk",
    )
    desktop: sdef_types.Specifier = Field(..., alias="desktop", description="the desktop")
    trash: sdef_types.Specifier = Field(..., alias="trash", description="the trash")
    home: sdef_types.Specifier = Field(..., alias="home", description="the home directory")
    computer_container: sdef_types.Specifier = Field(
        ...,
        alias="computer container",
        description="the computer location (as in Go > Computer)",
    )
    finder_preferences: sdef_types.Specifier = Field(
        ...,
        alias="Finder preferences",
        description="Various preferences that apply to the Finder as a whole",
    )
