from __future__ import annotations

# ruff: noqa: D301, D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar

from pydantic import Field

import openmac._internal.sdef.types as sdef_types
from openmac._internal.sdef import meta as sdef_meta
from openmac._internal.sdef.base import SDEFCommand


class OpenVirtualLocationCommand(SDEFCommand):
    """Private event to open a virtual location\n\nSDEF extras: {"direct_parameters": [{"access_group": [{"identifier": "com.apple.private.siri"}], "description": "the location to open", "type": "text", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="openVirtualLocation",
        code="fndrovir",
        description="Private event to open a virtual location",
        hidden=True,
        direct_parameter_type="text",
        parameters=(),
        results=(),
        access_groups=(
            (
                "com.apple.private.siri",
                None,
            ),
            (
                "com.apple.private.siri",
                None,
            ),
        ),
    )
    direct_parameter: str = Field(
        ...,
        description="the location to open",
        json_schema_extra={"access_groups": [{"identifier": "com.apple.private.siri"}]},
    )

    def __call__(self) -> None:
        raise NotImplementedError


class CopyCommand(SDEFCommand):
    """(NOT AVAILABLE YET) Copy the selected items to the clipboard (the Finder must be the front application)"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="copy",
        code="misccopy",
        description="(NOT AVAILABLE YET) Copy the selected items to the clipboard (the Finder must be the front application)",
        hidden=None,
        direct_parameter_type=None,
        parameters=(),
        results=(),
        access_groups=(),
    )

    def __call__(self) -> None:
        raise NotImplementedError


class SortCommand(SDEFCommand):
    """Return the specified object(s) in a sorted list\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "a list of finder objects to sort", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [], "code": "by  ", "description": "the property to sort the items by (name, index, date, etc.)", "name": "by", "type": "property", "type_element": []}], "results": [{"description": "the sorted items in their new order", "optional": "yes", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="sort",
        code="DATASORT",
        description="Return the specified object(s) in a sorted list",
        hidden=None,
        direct_parameter_type="specifier",
        parameters=(
            sdef_meta.ParameterMeta(
                name="by",
                code="by  ",
                type="property",
                description="the property to sort the items by (name, index, date, etc.)",
                optional=None,
                hidden=None,
                requires_access=None,
            ),
        ),
        results=(
            sdef_meta.ResultMeta(
                type="specifier",
                description="the sorted items in their new order",
                optional=True,
            ),
        ),
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier = Field(
        ...,
        description="a list of finder objects to sort",
    )
    by: sdef_types.Specifier = Field(
        ...,
        alias="by",
        description="the property to sort the items by (name, index, date, etc.)",
    )

    def __call__(self) -> sdef_types.Specifier | None:
        raise NotImplementedError
