from __future__ import annotations

# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from enum import Enum
from typing import Final

from openmac._internal.sdef import meta as sdef_meta


class Priv(str, Enum):
    """Generated from SDEF."""

    READ_ONLY = "read"
    READ_WRITE = "rdwr"
    WRITE_ONLY = "writ"
    NONE = "none"


PRIV_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="priv",
    code="priv",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="read only", code="read", description=None),
        sdef_meta.EnumeratorMeta(name="read write", code="rdwr", description=None),
        sdef_meta.EnumeratorMeta(name="write only", code="writ", description=None),
        sdef_meta.EnumeratorMeta(name="none", code="none", description=None),
    ),
)
