from __future__ import annotations

# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import Final

from openmac._internal.sdef import meta as sdef_meta

SUITE_META: Final[sdef_meta.SuiteMeta] = sdef_meta.SuiteMeta(
    name="Finder items",
    code="fndr",
    description="Commands used with file system items, and basic item definition",
    hidden=None,
)
