from __future__ import annotations

from openmac.finder.sdef.suites.containers_and_folders_suite import ContainersAndFoldersSuite
from openmac.finder.sdef.suites.enumerations_suite import EnumerationsSuite
from openmac.finder.sdef.suites.files_suite import FilesSuite
from openmac.finder.sdef.suites.finder_basics_suite import FinderBasicsSuite
from openmac.finder.sdef.suites.finder_items_suite import FinderItemsSuite
from openmac.finder.sdef.suites.legacy_suite import LegacySuite

# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from openmac.finder.sdef.suites.standard_suite import StandardSuite
from openmac.finder.sdef.suites.type_definitions_suite import TypeDefinitionsSuite
from openmac.finder.sdef.suites.window_classes_suite import WindowClassesSuite

__all__ = [
    "ContainersAndFoldersSuite",
    "EnumerationsSuite",
    "FilesSuite",
    "FinderBasicsSuite",
    "FinderItemsSuite",
    "LegacySuite",
    "StandardSuite",
    "TypeDefinitionsSuite",
    "WindowClassesSuite",
]
