from __future__ import annotations

# ruff: noqa: D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar, Final

from pydantic import Field

import openmac._internal.sdef.types as sdef_types
from openmac._internal.sdef import meta as sdef_meta
from openmac._internal.sdef.base import SDEFClass, SDEFCommand

SUITE_META: Final[sdef_meta.SuiteMeta] = sdef_meta.SuiteMeta(
    name="Files",
    code="fndr",
    description="Classes representing files",
    hidden=None,
)


class File(SDEFClass):
    """A file"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="file",
        code="file",
        description="A file",
        hidden=None,
        inherits="item",
        plural="files",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="file type",
                code="asty",
                type="type",
                description="the OSType identifying the type of data contained in the item",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="creator type",
                code="fcrt",
                type="type",
                description="the OSType identifying the application that created the item",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="stationery",
                code="pspd",
                type="boolean",
                description="Is the file a stationery pad?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="product version",
                code="ver2",
                type="text",
                description='the version of the product (visible at the top of the "Get Info" window)',
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="version",
                code="vers",
                type="text",
                description='the version of the file (visible at the bottom of the "Get Info" window)',
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    file_type: str = Field(
        ...,
        alias="file type",
        description="the OSType identifying the type of data contained in the item",
    )
    creator_type: str = Field(
        ...,
        alias="creator type",
        description="the OSType identifying the application that created the item",
    )
    stationery: bool = Field(..., alias="stationery", description="Is the file a stationery pad?")
    product_version: str = Field(
        ...,
        alias="product version",
        description='the version of the product (visible at the top of the "Get Info" window)',
    )
    version: str = Field(
        ...,
        alias="version",
        description='the version of the file (visible at the bottom of the "Get Info" window)',
    )


class AliasFile(File):
    """An alias file (created with "Make Alias")"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="alias file",
        code="alia",
        description='An alias file (created with "Make Alias")',
        hidden=None,
        inherits="file",
        plural="alias files",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="original item",
                code="orig",
                type="specifier",
                description="the original item pointed to by the alias",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    original_item: sdef_types.Specifier = Field(
        ...,
        alias="original item",
        description="the original item pointed to by the alias",
    )


class ApplicationFile(File):
    """An application's file on disk"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="application file",
        code="appf",
        description="An application's file on disk",
        hidden=None,
        inherits="file",
        plural="application files",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="id",
                code="ID  ",
                type="text",
                description="the bundle identifier or creator type of the application",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="suggested size",
                code="sprt",
                type="integer",
                description="(AVAILABLE IN 10.1 TO 10.4) the memory size with which the developer recommends the application be launched",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="minimum size",
                code="mprt",
                type="integer",
                description="(AVAILABLE IN 10.1 TO 10.4) the smallest memory size with which the application can be launched",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="preferred size",
                code="appt",
                type="integer",
                description="(AVAILABLE IN 10.1 TO 10.4) the memory size with which the application will be launched",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="accepts high level events",
                code="isab",
                type="boolean",
                description="Is the application high-level event aware? (OBSOLETE: always returns true)",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="has scripting terminology",
                code="hscr",
                type="boolean",
                description="Does the process have a scripting terminology, i.e., can it be scripted?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="opens in Classic",
                code="Clsc",
                type="boolean",
                description="(AVAILABLE IN 10.1 TO 10.4) Should the application launch in the Classic environment?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    id_: str = Field(
        ...,
        alias="id",
        description="the bundle identifier or creator type of the application",
    )
    suggested_size: int = Field(
        ...,
        alias="suggested size",
        description="(AVAILABLE IN 10.1 TO 10.4) the memory size with which the developer recommends the application be launched",
    )
    minimum_size: int = Field(
        ...,
        alias="minimum size",
        description="(AVAILABLE IN 10.1 TO 10.4) the smallest memory size with which the application can be launched",
    )
    preferred_size: int = Field(
        ...,
        alias="preferred size",
        description="(AVAILABLE IN 10.1 TO 10.4) the memory size with which the application will be launched",
    )
    accepts_high_level_events: bool = Field(
        ...,
        alias="accepts high level events",
        description="Is the application high-level event aware? (OBSOLETE: always returns true)",
    )
    has_scripting_terminology: bool = Field(
        ...,
        alias="has scripting terminology",
        description="Does the process have a scripting terminology, i.e., can it be scripted?",
    )
    opens_in_classic: bool = Field(
        ...,
        alias="opens in Classic",
        description="(AVAILABLE IN 10.1 TO 10.4) Should the application launch in the Classic environment?",
    )


class DocumentFile(File):
    """A document file"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="document file",
        code="docf",
        description="A document file",
        hidden=None,
        inherits="file",
        plural="document files",
        id=None,
        properties=(),
        elements=(),
        responds_to=(),
    )


class InternetLocationFile(File):
    """A file containing an internet location"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="internet location file",
        code="inlf",
        description="A file containing an internet location",
        hidden=None,
        inherits="file",
        plural="internet location files",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="location",
                code="iloc",
                type="text",
                description="the internet location",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    location: str = Field(..., alias="location", description="the internet location")


class Clipping(File):
    """A clipping"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="clipping",
        code="clpf",
        description="A clipping",
        hidden=None,
        inherits="file",
        plural="clippings",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="clipping window",
                code="lwnd",
                type="specifier",
                description="(NOT AVAILABLE YET) the clipping window for this clipping",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    clipping_window: sdef_types.Specifier = Field(
        ...,
        alias="clipping window",
        description="(NOT AVAILABLE YET) the clipping window for this clipping",
    )


class Package(SDEFClass):
    """A package"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="package",
        code="pack",
        description="A package",
        hidden=None,
        inherits="item",
        plural="packages",
        id=None,
        properties=(),
        elements=(),
        responds_to=(),
    )


class FilesSuite:
    """Classes representing files"""

    COMMANDS: ClassVar[tuple[type[SDEFCommand], ...]] = ()


__all__ = [
    "AliasFile",
    "ApplicationFile",
    "Clipping",
    "DocumentFile",
    "File",
    "FilesSuite",
    "InternetLocationFile",
    "Package",
]
