from __future__ import annotations

from enum import Enum

# ruff: noqa: D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar, Final

from pydantic import Field

import openmac._internal.sdef as sdef_types
from openmac._internal import sdef_meta
from openmac._internal.models import MacModel

SUITE_META: Final[sdef_meta.SuiteMeta] = sdef_meta.SuiteMeta(
    name="Containers and folders",
    code="fndr",
    description="Classes that can contain other file system items",
    hidden=None,
)


class Container(MacModel):
    """An item that contains other items"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="container",
        code="ctnr",
        description="An item that contains other items",
        hidden=None,
        inherits="item",
        plural="containers",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="entire contents",
                code="ects",
                type="specifier",
                description="the entire contents of the container, including the contents of its children",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="expandable",
                code="pexa",
                type="boolean",
                description="(NOT AVAILABLE YET) Is the container capable of being expanded as an outline?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="expanded",
                code="pexp",
                type="boolean",
                description="(NOT AVAILABLE YET) Is the container opened as an outline? (can only be set for containers viewed as lists)",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="completely expanded",
                code="pexc",
                type="boolean",
                description="(NOT AVAILABLE YET) Are the container and all of its children opened as outlines? (can only be set for containers viewed as lists)",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="container window",
                code="cwnd",
                type="specifier",
                description="the container window for this folder",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(type="item", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="container", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="folder", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="alias file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="application file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="document file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="internet location file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="clipping", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="package", description=None, hidden=None, access=None),
        ),
        responds_to=(),
    )
    entire_contents: sdef_types.Specifier = Field(
        ...,
        alias="entire contents",
        description="the entire contents of the container, including the contents of its children",
    )
    expandable: bool = Field(
        ...,
        alias="expandable",
        description="(NOT AVAILABLE YET) Is the container capable of being expanded as an outline?",
    )
    expanded: bool = Field(
        ...,
        alias="expanded",
        description="(NOT AVAILABLE YET) Is the container opened as an outline? (can only be set for containers viewed as lists)",
    )
    completely_expanded: bool = Field(
        ...,
        alias="completely expanded",
        description="(NOT AVAILABLE YET) Are the container and all of its children opened as outlines? (can only be set for containers viewed as lists)",
    )
    container_window: sdef_types.Specifier = Field(
        ...,
        alias="container window",
        description="the container window for this folder",
    )


class ComputerObject(MacModel):
    """the Computer location (as in Go > Computer)"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="computer-object",
        code="ccmp",
        description="the Computer location (as in Go > Computer)",
        hidden=None,
        inherits="item",
        plural=None,
        id=None,
        properties=(),
        elements=(),
        responds_to=(),
    )


class Disk(Container):
    """A disk"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="disk",
        code="cdis",
        description="A disk",
        hidden=None,
        inherits="container",
        plural="disks",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="id",
                code="ID  ",
                type="integer",
                description="the unique id for this disk (unchanged while disk remains connected and Finder remains running)",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="capacity",
                code="capa",
                type="double integer",
                description="the total number of bytes (free or used) on the disk",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="free space",
                code="frsp",
                type="double integer",
                description="the number of free bytes left on the disk",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="ejectable",
                code="isej",
                type="boolean",
                description="Can the media be ejected (floppies, CDs, and so on)?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="local volume",
                code="isrv",
                type="boolean",
                description="Is the media a local volume (as opposed to a file server)?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="startup",
                code="istd",
                type="boolean",
                description="Is this disk the boot disk?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="format",
                code="dfmt",
                type="edfm",
                description="the filesystem format of this disk",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="journaling enabled",
                code="Jrnl",
                type="boolean",
                description="Does this disk do file system journaling?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="ignore privileges",
                code="igpr",
                type="boolean",
                description="Ignore permissions on this disk?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(type="item", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="container", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="folder", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="alias file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="application file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="document file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="internet location file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="clipping", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="package", description=None, hidden=None, access=None),
        ),
        responds_to=(),
    )
    id_: int = Field(
        ...,
        alias="id",
        description="the unique id for this disk (unchanged while disk remains connected and Finder remains running)",
    )
    capacity: int = Field(
        ...,
        alias="capacity",
        description="the total number of bytes (free or used) on the disk",
    )
    free_space: int = Field(
        ...,
        alias="free space",
        description="the number of free bytes left on the disk",
    )
    ejectable: bool = Field(
        ...,
        alias="ejectable",
        description="Can the media be ejected (floppies, CDs, and so on)?",
    )
    local_volume: bool = Field(
        ...,
        alias="local volume",
        description="Is the media a local volume (as opposed to a file server)?",
    )
    startup: bool = Field(..., alias="startup", description="Is this disk the boot disk?")
    format_: Edfm = Field(..., alias="format", description="the filesystem format of this disk")
    journaling_enabled: bool = Field(
        ...,
        alias="journaling enabled",
        description="Does this disk do file system journaling?",
    )
    ignore_privileges: bool = Field(
        ...,
        alias="ignore privileges",
        description="Ignore permissions on this disk?",
    )


class Folder(Container):
    """A folder"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="folder",
        code="cfol",
        description="A folder",
        hidden=None,
        inherits="container",
        plural="folders",
        id=None,
        properties=(),
        elements=(
            sdef_meta.ElementMeta(type="item", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="container", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="folder", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="alias file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="application file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="document file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="internet location file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="clipping", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="package", description=None, hidden=None, access=None),
        ),
        responds_to=(),
    )


class DesktopObject(Container):
    """Desktop-object is the class of the "desktop" object"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="desktop-object",
        code="cdsk",
        description='Desktop-object is the class of the "desktop" object',
        hidden=None,
        inherits="container",
        plural=None,
        id=None,
        properties=(),
        elements=(
            sdef_meta.ElementMeta(type="item", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="container", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="disk", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="folder", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="alias file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="application file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="document file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="internet location file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="clipping", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="package", description=None, hidden=None, access=None),
        ),
        responds_to=(),
    )


class TrashObject(Container):
    """Trash-object is the class of the "trash" object"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="trash-object",
        code="ctrs",
        description='Trash-object is the class of the "trash" object',
        hidden=None,
        inherits="container",
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="warns before emptying",
                code="warn",
                type="boolean",
                description="Display a dialog when emptying the trash?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(type="item", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="container", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="folder", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="alias file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="application file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="document file", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(
                type="internet location file",
                description=None,
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(type="clipping", description=None, hidden=None, access=None),
            sdef_meta.ElementMeta(type="package", description=None, hidden=None, access=None),
        ),
        responds_to=(),
    )
    warns_before_emptying: bool = Field(
        ...,
        alias="warns before emptying",
        description="Display a dialog when emptying the trash?",
    )


class Edfm(str, Enum):
    """Generated from SDEF."""

    MAC_OS_FORMAT = "dfhf"
    MAC_OS_EXTENDED_FORMAT = "dfh+"
    UFS_FORMAT = "dfuf"
    NFS_FORMAT = "dfnf"
    AUDIO_FORMAT = "dfau"
    PRO_DOS_FORMAT = "dfpr"
    MSDOS_FORMAT = "dfms"
    NTFS_FORMAT = "dfnt"
    ISO_9660_FORMAT = "df96"
    HIGH_SIERRA_FORMAT = "dfhs"
    QUICK_TAKE_FORMAT = "dfqt"
    APPLE_PHOTO_FORMAT = "dfph"
    APPLE_SHARE_FORMAT = "dfas"
    UDF_FORMAT = "dfud"
    WEB_DAV_FORMAT = "dfwd"
    FTP_FORMAT = "dfft"
    PACKET_WRITTEN_UDF_FORMAT = "dfpu"
    XSAN_FORMAT = "dfac"
    APFS_FORMAT = "dfap"
    EX_FAT_FORMAT = "dfxf"
    SMB_FORMAT = "dfsm"
    UNKNOWN_FORMAT = "df??"


EDFM_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="edfm",
    code="edfm",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="Mac OS format", code="dfhf", description=None),
        sdef_meta.EnumeratorMeta(name="Mac OS Extended format", code="dfh+", description=None),
        sdef_meta.EnumeratorMeta(name="UFS format", code="dfuf", description=None),
        sdef_meta.EnumeratorMeta(name="NFS format", code="dfnf", description=None),
        sdef_meta.EnumeratorMeta(name="audio format", code="dfau", description=None),
        sdef_meta.EnumeratorMeta(name="ProDOS format", code="dfpr", description=None),
        sdef_meta.EnumeratorMeta(name="MSDOS format", code="dfms", description=None),
        sdef_meta.EnumeratorMeta(name="NTFS format", code="dfnt", description=None),
        sdef_meta.EnumeratorMeta(name="ISO 9660 format", code="df96", description=None),
        sdef_meta.EnumeratorMeta(name="High Sierra format", code="dfhs", description=None),
        sdef_meta.EnumeratorMeta(name="QuickTake format", code="dfqt", description=None),
        sdef_meta.EnumeratorMeta(name="Apple Photo format", code="dfph", description=None),
        sdef_meta.EnumeratorMeta(name="AppleShare format", code="dfas", description=None),
        sdef_meta.EnumeratorMeta(name="UDF format", code="dfud", description=None),
        sdef_meta.EnumeratorMeta(name="WebDAV format", code="dfwd", description=None),
        sdef_meta.EnumeratorMeta(name="FTP format", code="dfft", description=None),
        sdef_meta.EnumeratorMeta(name="Packet written UDF format", code="dfpu", description=None),
        sdef_meta.EnumeratorMeta(name="Xsan format", code="dfac", description=None),
        sdef_meta.EnumeratorMeta(name="APFS format", code="dfap", description=None),
        sdef_meta.EnumeratorMeta(name="ExFAT format", code="dfxf", description=None),
        sdef_meta.EnumeratorMeta(name="SMB format", code="dfsm", description=None),
        sdef_meta.EnumeratorMeta(name="unknown format", code="df??", description=None),
    ),
)


class ContainersAndFoldersSuite:
    """Classes that can contain other file system items"""

    COMMANDS: ClassVar[tuple[sdef_meta.CommandMeta, ...]] = ()


__all__ = [
    "ComputerObject",
    "Container",
    "ContainersAndFoldersSuite",
    "DesktopObject",
    "Disk",
    "Edfm",
    "Folder",
    "TrashObject",
]
