from __future__ import annotations

from enum import Enum

# ruff: noqa: D301, D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar, Final

from pydantic import Field

import openmac._internal.sdef as sdef_types
from openmac._internal import sdef_meta
from openmac._internal.models import SDEFCommand, SDEFModel

SUITE_META: Final[sdef_meta.SuiteMeta] = sdef_meta.SuiteMeta(
    name="Finder items",
    code="fndr",
    description="Commands used with file system items, and basic item definition",
    hidden=None,
)


class Item(SDEFModel):
    """An item"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="item",
        code="cobj",
        description="An item",
        hidden=None,
        inherits=None,
        plural="items",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="name",
                code="pnam",
                type="text",
                description="the name of the item",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="displayed name",
                code="dnam",
                type="text",
                description="the user-visible name of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="name extension",
                code="nmxt",
                type="text",
                description='the name extension of the item (such as "txt")',
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="extension hidden",
                code="hidx",
                type="boolean",
                description="Is the item's extension hidden from the user?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="index",
                code="pidx",
                type="integer",
                description="the index in the front-to-back ordering within its container",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="container",
                code="ctnr",
                type="specifier",
                description="the container of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="disk",
                code="cdis",
                type="specifier",
                description="the disk on which the item is stored",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="position",
                code="posn",
                type="point",
                description="the position of the item within its parent window (can only be set for an item in a window viewed as icons or buttons)",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="desktop position",
                code="dpos",
                type="point",
                description="the position of the item on the desktop",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="bounds",
                code="pbnd",
                type="rectangle",
                description="the bounding rectangle of the item (can only be set for an item in a window viewed as icons or buttons)",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="label index",
                code="labi",
                type="integer",
                description="the label of the item",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="locked",
                code="aslk",
                type="boolean",
                description="Is the file locked?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="kind",
                code="kind",
                type="text",
                description="the kind of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="description",
                code="dscr",
                type="text",
                description="a description of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="comment",
                code="comt",
                type="text",
                description='the comment of the item, displayed in the "Get Info" window',
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="size",
                code="ptsz",
                type="double integer",
                description="the logical size of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="physical size",
                code="phys",
                type="double integer",
                description="the actual space used by the item on disk",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="creation date",
                code="ascd",
                type="date",
                description="the date on which the item was created",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="modification date",
                code="asmo",
                type="date",
                description="the date on which the item was last modified",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="icon",
                code="iimg",
                type="icon family",
                description="the icon bitmap of the item",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="URL",
                code="pURL",
                type="text",
                description="the URL of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="owner",
                code="sown",
                type="text",
                description="the user that owns the container",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="group",
                code="sgrp",
                type="text",
                description="the user or group that has special access to the container",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="owner privileges",
                code="ownr",
                type="priv",
                description=None,
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="group privileges",
                code="gppr",
                type="priv",
                description=None,
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="everyones privileges",
                code="gstp",
                type="priv",
                description=None,
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="information window",
                code="iwnd",
                type="specifier",
                description="the information window for the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="properties",
                code="pALL",
                type="record",
                description="every property of an item",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="class",
                code="pcls",
                type="type",
                description="the class of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    name: str = Field(..., alias="name", description="the name of the item")
    displayed_name: str = Field(
        ...,
        alias="displayed name",
        description="the user-visible name of the item",
    )
    name_extension: str = Field(
        ...,
        alias="name extension",
        description='the name extension of the item (such as "txt")',
    )
    extension_hidden: bool = Field(
        ...,
        alias="extension hidden",
        description="Is the item's extension hidden from the user?",
    )
    index: int = Field(
        ...,
        alias="index",
        description="the index in the front-to-back ordering within its container",
    )
    container: sdef_types.Specifier = Field(
        ...,
        alias="container",
        description="the container of the item",
    )
    disk: sdef_types.Specifier = Field(
        ...,
        alias="disk",
        description="the disk on which the item is stored",
    )
    position: sdef_types.Point = Field(
        ...,
        alias="position",
        description="the position of the item within its parent window (can only be set for an item in a window viewed as icons or buttons)",
    )
    desktop_position: sdef_types.Point = Field(
        ...,
        alias="desktop position",
        description="the position of the item on the desktop",
    )
    bounds: sdef_types.Rectangle = Field(
        ...,
        alias="bounds",
        description="the bounding rectangle of the item (can only be set for an item in a window viewed as icons or buttons)",
    )
    label_index: int = Field(..., alias="label index", description="the label of the item")
    locked: bool = Field(..., alias="locked", description="Is the file locked?")
    kind: str = Field(..., alias="kind", description="the kind of the item")
    description: str = Field(..., alias="description", description="a description of the item")
    comment: str = Field(
        ...,
        alias="comment",
        description='the comment of the item, displayed in the "Get Info" window',
    )
    size: int = Field(..., alias="size", description="the logical size of the item")
    physical_size: int = Field(
        ...,
        alias="physical size",
        description="the actual space used by the item on disk",
    )
    creation_date: sdef_types.Date = Field(
        ...,
        alias="creation date",
        description="the date on which the item was created",
    )
    modification_date: sdef_types.Date = Field(
        ...,
        alias="modification date",
        description="the date on which the item was last modified",
    )
    icon: sdef_types.Specifier = Field(..., alias="icon", description="the icon bitmap of the item")
    url: str = Field(..., alias="URL", description="the URL of the item")
    owner: str = Field(..., alias="owner", description="the user that owns the container")
    group: str = Field(
        ...,
        alias="group",
        description="the user or group that has special access to the container",
    )
    owner_privileges: Priv = Field(..., alias="owner privileges", description=None)
    group_privileges: Priv = Field(..., alias="group privileges", description=None)
    everyones_privileges: Priv = Field(..., alias="everyones privileges", description=None)
    information_window: sdef_types.Specifier = Field(
        ...,
        alias="information window",
        description="the information window for the item",
    )
    properties: sdef_types.Record = Field(
        ...,
        alias="properties",
        description="every property of an item",
    )
    class_: str = Field(..., alias="class", description="the class of the item")


class Priv(str, Enum):
    """Generated from SDEF."""

    READ_ONLY = "read"
    READ_WRITE = "rdwr"
    WRITE_ONLY = "writ"
    NONE = "none"


PRIV_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="priv",
    code="priv",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="read only", code="read", description=None),
        sdef_meta.EnumeratorMeta(name="read write", code="rdwr", description=None),
        sdef_meta.EnumeratorMeta(name="write only", code="writ", description=None),
        sdef_meta.EnumeratorMeta(name="none", code="none", description=None),
    ),
)


class CleanUpCommand(SDEFCommand):
    """Arrange items in window nicely (only applies to open windows in icon view that are not kept arranged)\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the window to clean up", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [], "code": "by  ", "description": "the order in which to clean up the objects (name, index, date, etc.)", "name": "by", "optional": "yes", "type": "property", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="clean up",
        code="fndrfclu",
        description="Arrange items in window nicely (only applies to open windows in icon view that are not kept arranged)",
        hidden=None,
        direct_parameter_type="specifier",
        parameters=(
            sdef_meta.ParameterMeta(
                name="by",
                code="by  ",
                type="property",
                description="the order in which to clean up the objects (name, index, date, etc.)",
                optional=True,
                hidden=None,
                requires_access=None,
            ),
        ),
        results=(),
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier = Field(..., description="the window to clean up")
    by: sdef_types.Specifier | None = Field(
        default=None,
        alias="by",
        description="the order in which to clean up the objects (name, index, date, etc.)",
    )

    def __call__(self) -> None:
        raise NotImplementedError


class EjectCommand(SDEFCommand):
    """Eject the specified disk(s)\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the disk(s) to eject", "optional": "yes", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="eject",
        code="fndrejct",
        description="Eject the specified disk(s)",
        hidden=None,
        direct_parameter_type="specifier",
        parameters=(),
        results=(),
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier | None = Field(
        default=None,
        description="the disk(s) to eject",
    )

    def __call__(self) -> None:
        raise NotImplementedError


class EmptyCommand(SDEFCommand):
    """Empty the trash\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "\\"empty\\" and \\"empty trash\\" both do the same thing", "optional": "yes", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [], "code": "sec?", "description": "(obsolete)", "name": "security", "optional": "yes", "type": "boolean", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="empty",
        code="fndrempt",
        description="Empty the trash",
        hidden=None,
        direct_parameter_type="specifier",
        parameters=(
            sdef_meta.ParameterMeta(
                name="security",
                code="sec?",
                type="boolean",
                description="(obsolete)",
                optional=True,
                hidden=None,
                requires_access=None,
            ),
        ),
        results=(),
        access_groups=(
            (
                "com.apple.finder.trash",
                None,
            ),
        ),
    )
    direct_parameter: sdef_types.Specifier | None = Field(
        default=None,
        description='"empty" and "empty trash" both do the same thing',
    )
    security: bool | None = Field(default=None, alias="security", description="(obsolete)")

    def __call__(self) -> None:
        raise NotImplementedError


class EraseCommand(SDEFCommand):
    """(NOT AVAILABLE) Erase the specified disk(s)\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the items to erase", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="erase",
        code="fndrfera",
        description="(NOT AVAILABLE) Erase the specified disk(s)",
        hidden=None,
        direct_parameter_type="specifier",
        parameters=(),
        results=(),
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier = Field(..., description="the items to erase")

    def __call__(self) -> None:
        raise NotImplementedError


class RevealCommand(SDEFCommand):
    """Bring the specified object(s) into view\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the object to be made visible", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="reveal",
        code="miscmvis",
        description="Bring the specified object(s) into view",
        hidden=None,
        direct_parameter_type="specifier",
        parameters=(),
        results=(),
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier = Field(..., description="the object to be made visible")

    def __call__(self) -> None:
        raise NotImplementedError


class UpdateCommand(SDEFCommand):
    """Update the display of the specified object(s) to match their on-disk representation\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the item to update", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [], "code": "nec?", "description": "only update if necessary (i.e. a finder window is open). default is false", "name": "necessity", "optional": "yes", "type": "boolean", "type_element": []}, {"cocoa": [], "code": "reg?", "description": "register applications. default is true", "name": "registering applications", "optional": "yes", "type": "boolean", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="update",
        code="fndrfupd",
        description="Update the display of the specified object(s) to match their on-disk representation",
        hidden=None,
        direct_parameter_type="specifier",
        parameters=(
            sdef_meta.ParameterMeta(
                name="necessity",
                code="nec?",
                type="boolean",
                description="only update if necessary (i.e. a finder window is open). default is false",
                optional=True,
                hidden=None,
                requires_access=None,
            ),
            sdef_meta.ParameterMeta(
                name="registering applications",
                code="reg?",
                type="boolean",
                description="register applications. default is true",
                optional=True,
                hidden=None,
                requires_access=None,
            ),
        ),
        results=(),
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier = Field(..., description="the item to update")
    necessity: bool | None = Field(
        default=None,
        alias="necessity",
        description="only update if necessary (i.e. a finder window is open). default is false",
    )
    registering_applications: bool | None = Field(
        default=None,
        alias="registering applications",
        description="register applications. default is true",
    )

    def __call__(self) -> None:
        raise NotImplementedError


class FinderItemsSuite:
    """Commands used with file system items, and basic item definition"""

    COMMANDS: ClassVar[tuple[type[SDEFCommand], ...]] = (
        CleanUpCommand,
        EjectCommand,
        EmptyCommand,
        EraseCommand,
        RevealCommand,
        UpdateCommand,
    )


__all__ = [
    "CleanUpCommand",
    "EjectCommand",
    "EmptyCommand",
    "EraseCommand",
    "FinderItemsSuite",
    "Item",
    "Priv",
    "RevealCommand",
    "UpdateCommand",
]
