from __future__ import annotations

# ruff: noqa: D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar, Final

from pydantic import Field

import openmac._internal.sdef as sdef_types
import openmac.finder.suites.finder_basics_suite as finder_basics_suite_module
from openmac._internal import sdef_meta
from openmac._internal.models import SDEFClass, SDEFCommand

SUITE_META: Final[sdef_meta.SuiteMeta] = sdef_meta.SuiteMeta(
    name="Legacy suite",
    code="fleg",
    description="Operations formerly handled by the Finder, but now automatically delegated to other applications",
    hidden=None,
)


class Process(SDEFClass):
    """A process running on this computer"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="process",
        code="prcs",
        description="A process running on this computer",
        hidden=None,
        inherits=None,
        plural="processes",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="name",
                code="pnam",
                type="text",
                description="the name of the process",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="visible",
                code="pvis",
                type="boolean",
                description="Is the process' layer visible?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="frontmost",
                code="pisf",
                type="boolean",
                description="Is the process the frontmost process?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="file",
                code="file",
                type="specifier",
                description="the file from which the process was launched",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="file type",
                code="asty",
                type="type",
                description="the OSType of the file type of the process",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="creator type",
                code="fcrt",
                type="type",
                description="the OSType of the creator of the process (the signature)",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="accepts high level events",
                code="isab",
                type="boolean",
                description="Is the process high-level event aware (accepts open application, open document, print document, and quit)?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="accepts remote events",
                code="revt",
                type="boolean",
                description="Does the process accept remote events?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="has scripting terminology",
                code="hscr",
                type="boolean",
                description="Does the process have a scripting terminology, i.e., can it be scripted?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="total partition size",
                code="appt",
                type="integer",
                description="the size of the partition with which the process was launched",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="partition space used",
                code="pusd",
                type="integer",
                description="the number of bytes currently used in the process' partition",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    name: str = Field(..., alias="name", description="the name of the process")
    visible: bool = Field(..., alias="visible", description="Is the process' layer visible?")
    frontmost: bool = Field(
        ...,
        alias="frontmost",
        description="Is the process the frontmost process?",
    )
    file: sdef_types.Specifier = Field(
        ...,
        alias="file",
        description="the file from which the process was launched",
    )
    file_type: str = Field(
        ...,
        alias="file type",
        description="the OSType of the file type of the process",
    )
    creator_type: str = Field(
        ...,
        alias="creator type",
        description="the OSType of the creator of the process (the signature)",
    )
    accepts_high_level_events: bool = Field(
        ...,
        alias="accepts high level events",
        description="Is the process high-level event aware (accepts open application, open document, print document, and quit)?",
    )
    accepts_remote_events: bool = Field(
        ...,
        alias="accepts remote events",
        description="Does the process accept remote events?",
    )
    has_scripting_terminology: bool = Field(
        ...,
        alias="has scripting terminology",
        description="Does the process have a scripting terminology, i.e., can it be scripted?",
    )
    total_partition_size: int = Field(
        ...,
        alias="total partition size",
        description="the size of the partition with which the process was launched",
    )
    partition_space_used: int = Field(
        ...,
        alias="partition space used",
        description="the number of bytes currently used in the process' partition",
    )


class ApplicationProcess(Process):
    """A process launched from an application file"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="application process",
        code="pcap",
        description="A process launched from an application file",
        hidden=None,
        inherits="process",
        plural="application processes",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="application file",
                code="appf",
                type="application file",
                description="the application file from which this process was launched",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    application_file: sdef_types.Specifier = Field(
        ...,
        alias="application file",
        description="the application file from which this process was launched",
    )


class DeskAccessoryProcess(Process):
    """A process launched from a desk accessory file"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="desk accessory process",
        code="pcda",
        description="A process launched from a desk accessory file",
        hidden=None,
        inherits="process",
        plural="desk accessory processes",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="desk accessory file",
                code="dafi",
                type="specifier",
                description="the desk accessory file from which this process was launched",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    desk_accessory_file: sdef_types.Specifier = Field(
        ...,
        alias="desk accessory file",
        description="the desk accessory file from which this process was launched",
    )


class Application(finder_basics_suite_module.Application):
    """The Finder"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="application",
        code=None,
        description="The Finder",
        hidden=None,
        inherits="application",
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="desktop picture",
                code="dpic",
                type="file",
                description="the desktop picture of the main monitor",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    desktop_picture: sdef_types.File = Field(
        ...,
        alias="desktop picture",
        description="the desktop picture of the main monitor",
    )


class RestartCommand(SDEFCommand):
    """Restart the computer"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="restart",
        code="fndrrest",
        description="Restart the computer",
        hidden=None,
        direct_parameter_type=None,
        parameters=(),
        results=(),
        access_groups=(),
    )

    def __call__(self) -> None:
        raise NotImplementedError


class ShutDownCommand(SDEFCommand):
    """Shut Down the computer"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="shut down",
        code="fndrshut",
        description="Shut Down the computer",
        hidden=None,
        direct_parameter_type=None,
        parameters=(),
        results=(),
        access_groups=(),
    )

    def __call__(self) -> None:
        raise NotImplementedError


class SleepCommand(SDEFCommand):
    """Put the computer to sleep"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="sleep",
        code="fndrslep",
        description="Put the computer to sleep",
        hidden=None,
        direct_parameter_type=None,
        parameters=(),
        results=(),
        access_groups=(),
    )

    def __call__(self) -> None:
        raise NotImplementedError


class LegacySuite:
    """Operations formerly handled by the Finder, but now automatically delegated to other applications"""

    COMMANDS: ClassVar[tuple[type[SDEFCommand], ...]] = (
        RestartCommand,
        ShutDownCommand,
        SleepCommand,
    )


__all__ = [
    "Application",
    "ApplicationProcess",
    "DeskAccessoryProcess",
    "LegacySuite",
    "Process",
    "RestartCommand",
    "ShutDownCommand",
    "SleepCommand",
]
