from __future__ import annotations

# ruff: noqa: D301, D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar, Final

import openmac._internal.sdef as sdef_types
from openmac._internal import sdef_meta

SUITE_META: Final[sdef_meta.SuiteMeta] = sdef_meta.SuiteMeta(
    name="Standard Suite",
    code="CoRe",
    description="Common terms that most applications should support",
    hidden=None,
)


class StandardSuite:
    """Common terms that most applications should support"""

    COMMANDS: ClassVar[tuple[sdef_meta.CommandMeta, ...]] = (
        sdef_meta.CommandMeta(
            name="open",
            code="aevtodoc",
            description="Open the specified object(s)",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(
                sdef_meta.ParameterMeta(
                    name="using",
                    code="usin",
                    type="specifier",
                    description="the application file to open the object with",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="with properties",
                    code="prdt",
                    type="record",
                    description="the initial values for the properties, to be included with the open command sent to the application that opens the direct object",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="print",
            code="aevtpdoc",
            description="Print the specified object(s)",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(
                sdef_meta.ParameterMeta(
                    name="with properties",
                    code="prdt",
                    type="record",
                    description="optional properties to be included with the print command sent to the application that prints the direct object",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="quit",
            code="aevtquit",
            description="Quit the Finder",
            hidden=None,
            direct_parameter_type=None,
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="activate",
            code="miscactv",
            description="Activate the specified window (or the Finder)",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="close",
            code="coreclos",
            description="Close an object",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="count",
            code="corecnte",
            description="Return the number of elements of a particular class within an object",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(
                sdef_meta.ParameterMeta(
                    name="each",
                    code="kocl",
                    type="type",
                    description="the class of the elements to be counted",
                    optional=None,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(
                sdef_meta.ResultMeta(
                    type="integer",
                    description="the number of elements",
                    optional=None,
                ),
            ),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="data size",
            code="coredsiz",
            description="Return the size in bytes of an object",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(
                sdef_meta.ParameterMeta(
                    name="as",
                    code="rtyp",
                    type="type",
                    description="the data type for which the size is calculated",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(
                sdef_meta.ResultMeta(
                    type="integer",
                    description="the size of the object in bytes",
                    optional=None,
                ),
            ),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="delete",
            code="coredelo",
            description="Move an item from its container to the trash",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(
                sdef_meta.ResultMeta(
                    type="specifier",
                    description="to the item that was just deleted",
                    optional=None,
                ),
            ),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="duplicate",
            code="coreclon",
            description="Duplicate one or more object(s)",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(
                sdef_meta.ParameterMeta(
                    name="to",
                    code="insh",
                    type="location specifier",
                    description="the new location for the object(s)",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="replacing",
                    code="alrp",
                    type="boolean",
                    description="Specifies whether or not to replace items in the destination that have the same name as items being duplicated",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="routing suppressed",
                    code="rout",
                    type="boolean",
                    description="Specifies whether or not to autoroute items (default is false). Only applies when copying to the system folder.",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="exact copy",
                    code="exct",
                    type="boolean",
                    description="Specifies whether or not to copy permissions/ownership as is",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(
                sdef_meta.ResultMeta(
                    type="specifier",
                    description="to the duplicated object(s)",
                    optional=None,
                ),
            ),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="exists",
            code="coredoex",
            description="Verify if an object exists",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(
                sdef_meta.ResultMeta(
                    type="boolean",
                    description="true if it exists, false if not",
                    optional=None,
                ),
            ),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="make",
            code="corecrel",
            description="Make a new element",
            hidden=None,
            direct_parameter_type=None,
            parameters=(
                sdef_meta.ParameterMeta(
                    name="new",
                    code="kocl",
                    type="type",
                    description="the class of the new element",
                    optional=None,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="at",
                    code="insh",
                    type="location specifier",
                    description="the location at which to insert the element",
                    optional=None,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="to",
                    code="to  ",
                    type="specifier",
                    description="when creating an alias file, the original item to create an alias to or when creating a file viewer window, the target of the window",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="with properties",
                    code="prdt",
                    type="record",
                    description="the initial values for the properties of the element",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(
                sdef_meta.ResultMeta(
                    type="specifier",
                    description="to the new object(s)",
                    optional=None,
                ),
            ),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="move",
            code="coremove",
            description="Move object(s) to a new location",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(
                sdef_meta.ParameterMeta(
                    name="to",
                    code="insh",
                    type="location specifier",
                    description="the new location for the object(s)",
                    optional=None,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="replacing",
                    code="alrp",
                    type="boolean",
                    description="Specifies whether or not to replace items in the destination that have the same name as items being moved",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="positioned at",
                    code="mvpl",
                    type="list",
                    description="Gives a list (in local window coordinates) of positions for the destination items",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
                sdef_meta.ParameterMeta(
                    name="routing suppressed",
                    code="rout",
                    type="boolean",
                    description="Specifies whether or not to autoroute items (default is false). Only applies when moving to the system folder.",
                    optional=True,
                    hidden=None,
                    requires_access=None,
                ),
            ),
            results=(
                sdef_meta.ResultMeta(
                    type="specifier",
                    description="to the object(s) after they have been moved",
                    optional=None,
                ),
            ),
            access_groups=(),
        ),
        sdef_meta.CommandMeta(
            name="select",
            code="miscslct",
            description="Select the specified object(s)",
            hidden=None,
            direct_parameter_type="specifier",
            parameters=(),
            results=(),
            access_groups=(),
        ),
    )

    def open_(
        self,
        direct_parameter: sdef_types.Specifier,
        *,
        using: sdef_types.Specifier | None = None,
        with_properties: sdef_types.Record | None = None,
    ) -> None:
        """Open the specified object(s)\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "list of objects to open", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [], "code": "usin", "description": "the application file to open the object with", "name": "using", "optional": "yes", "type": "specifier", "type_element": []}, {"cocoa": [], "code": "prdt", "description": "the initial values for the properties, to be included with the open command sent to the application that opens the direct object", "name": "with properties", "optional": "yes", "type": "record", "type_element": []}]}"""
        raise NotImplementedError

    def print_(
        self,
        direct_parameter: sdef_types.Specifier,
        *,
        with_properties: sdef_types.Record | None = None,
    ) -> None:
        """Print the specified object(s)\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "list of objects to print", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [], "code": "prdt", "description": "optional properties to be included with the print command sent to the application that prints the direct object", "name": "with properties", "optional": "yes", "type": "record", "type_element": []}]}"""
        raise NotImplementedError

    def quit_(self) -> None:
        """Quit the Finder"""
        raise NotImplementedError

    def activate(self, direct_parameter: sdef_types.Specifier | None = None) -> None:
        """Activate the specified window (or the Finder)\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the window to activate (if not specified, activates the Finder)", "optional": "yes", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def close(self, direct_parameter: sdef_types.Specifier) -> None:
        """Close an object\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the object to close", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def count(self, direct_parameter: sdef_types.Specifier, *, each: str) -> int:
        """Return the number of elements of a particular class within an object\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the object whose elements are to be counted", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [], "code": "kocl", "description": "the class of the elements to be counted", "name": "each", "type": "type", "type_element": []}], "results": [{"description": "the number of elements", "type": "integer", "type_element": []}]}"""
        raise NotImplementedError

    def data_size(self, direct_parameter: sdef_types.Specifier, *, as_: str | None = None) -> int:
        """Return the size in bytes of an object\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the object whose data size is to be returned", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [], "code": "rtyp", "description": "the data type for which the size is calculated", "name": "as", "optional": "yes", "type": "type", "type_element": []}], "results": [{"description": "the size of the object in bytes", "type": "integer", "type_element": []}]}"""
        raise NotImplementedError

    def delete(self, direct_parameter: sdef_types.Specifier) -> sdef_types.Specifier:
        """Move an item from its container to the trash\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the item to delete", "type": "specifier", "type_element": []}], "results": [{"description": "to the item that was just deleted", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def duplicate(
        self,
        direct_parameter: sdef_types.Specifier,
        *,
        to: sdef_types.LocationSpecifier | None = None,
        replacing: bool | None = None,
        routing_suppressed: bool | None = None,
        exact_copy: bool | None = None,
    ) -> sdef_types.Specifier:
        """Duplicate one or more object(s)\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the object(s) to duplicate", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [], "code": "insh", "description": "the new location for the object(s)", "name": "to", "optional": "yes", "type": "location specifier", "type_element": []}, {"cocoa": [], "code": "alrp", "description": "Specifies whether or not to replace items in the destination that have the same name as items being duplicated", "name": "replacing", "optional": "yes", "type": "boolean", "type_element": []}, {"cocoa": [], "code": "rout", "description": "Specifies whether or not to autoroute items (default is false). Only applies when copying to the system folder.", "name": "routing suppressed", "optional": "yes", "type": "boolean", "type_element": []}, {"cocoa": [], "code": "exct", "description": "Specifies whether or not to copy permissions/ownership as is", "name": "exact copy", "optional": "yes", "type": "boolean", "type_element": []}], "results": [{"description": "to the duplicated object(s)", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def exists(self, direct_parameter: sdef_types.Specifier) -> bool:
        """Verify if an object exists\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the object in question", "type": "specifier", "type_element": []}], "results": [{"description": "true if it exists, false if not", "type": "boolean", "type_element": []}]}"""
        raise NotImplementedError

    def make(
        self,
        *,
        new: str,
        at: sdef_types.LocationSpecifier,
        to: sdef_types.Specifier | None = None,
        with_properties: sdef_types.Record | None = None,
    ) -> sdef_types.Specifier:
        """Make a new element\n\nSDEF extras: {"parameters": [{"cocoa": [], "code": "kocl", "description": "the class of the new element", "name": "new", "type": "type", "type_element": []}, {"cocoa": [], "code": "insh", "description": "the location at which to insert the element", "name": "at", "type": "location specifier", "type_element": []}, {"cocoa": [], "code": "to  ", "description": "when creating an alias file, the original item to create an alias to or when creating a file viewer window, the target of the window", "name": "to", "optional": "yes", "type": "specifier", "type_element": []}, {"cocoa": [], "code": "prdt", "description": "the initial values for the properties of the element", "name": "with properties", "optional": "yes", "type": "record", "type_element": []}], "results": [{"description": "to the new object(s)", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def move(
        self,
        direct_parameter: sdef_types.Specifier,
        *,
        to: sdef_types.LocationSpecifier,
        replacing: bool | None = None,
        positioned_at: sdef_types.Specifier | None = None,
        routing_suppressed: bool | None = None,
    ) -> sdef_types.Specifier:
        """Move object(s) to a new location\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the object(s) to move", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [], "code": "insh", "description": "the new location for the object(s)", "name": "to", "type": "location specifier", "type_element": []}, {"cocoa": [], "code": "alrp", "description": "Specifies whether or not to replace items in the destination that have the same name as items being moved", "name": "replacing", "optional": "yes", "type": "boolean", "type_element": []}, {"cocoa": [], "code": "mvpl", "description": "Gives a list (in local window coordinates) of positions for the destination items", "name": "positioned at", "optional": "yes", "type": "list", "type_element": []}, {"cocoa": [], "code": "rout", "description": "Specifies whether or not to autoroute items (default is false). Only applies when moving to the system folder.", "name": "routing suppressed", "optional": "yes", "type": "boolean", "type_element": []}], "results": [{"description": "to the object(s) after they have been moved", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError

    def select(self, direct_parameter: sdef_types.Specifier) -> None:
        """Select the specified object(s)\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "the object to select", "type": "specifier", "type_element": []}]}"""
        raise NotImplementedError


__all__ = ["StandardSuite"]
