from __future__ import annotations

from enum import Enum

# ruff: noqa: D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar, Final

from pydantic import Field

import openmac._internal.sdef as sdef_types
from openmac._internal import sdef_meta
from openmac._internal.models import SDEFCommand, SDEFModel

SUITE_META: Final[sdef_meta.SuiteMeta] = sdef_meta.SuiteMeta(
    name="Type Definitions",
    code="tpdf",
    description="Definitions of records used in scripting the Finder",
    hidden=None,
)


class Preferences(SDEFModel):
    """The Finder Preferences"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="preferences",
        code="cprf",
        description="The Finder Preferences",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="window",
                code="cwin",
                type="preferences window",
                description="the window that would open if Finder preferences was opened",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="icon view options",
                code="icop",
                type="icon view options",
                description="the default icon view options",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="list view options",
                code="lvop",
                type="list view options",
                description="the default list view options",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="column view options",
                code="cvop",
                type="column view options",
                description="the column view options for all windows",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="folders spring open",
                code="sprg",
                type="boolean",
                description="Spring open folders after the specified delay?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="delay before springing",
                code="dela",
                type="real",
                description="the delay before springing open a container in seconds (from 0.167 to 1.169)",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="desktop shows hard disks",
                code="pdhd",
                type="boolean",
                description="Hard disks appear on the desktop?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="desktop shows external hard disks",
                code="pehd",
                type="boolean",
                description="External hard disks appear on the desktop?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="desktop shows removable media",
                code="pdrm",
                type="boolean",
                description="CDs, DVDs, and iPods appear on the desktop?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="desktop shows connected servers",
                code="pdsv",
                type="boolean",
                description="Connected servers appear on the desktop?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="new window target",
                code="pnwt",
                type="specifier",
                description="target location for a newly-opened Finder window",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="folders open in new windows",
                code="ponw",
                type="boolean",
                description="Folders open into new windows?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="folders open in new tabs",
                code="pont",
                type="boolean",
                description="Folders open into new tabs?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="new windows open in column view",
                code="pocv",
                type="boolean",
                description="Open new windows in column view?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="all name extensions showing",
                code="psnx",
                type="boolean",
                description='Show name extensions, even for items whose "extension hidden" is true?',
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    window: sdef_types.Specifier = Field(
        ...,
        alias="window",
        description="the window that would open if Finder preferences was opened",
    )
    icon_view_options: IconViewOptions = Field(
        ...,
        alias="icon view options",
        description="the default icon view options",
    )
    list_view_options: ListViewOptions = Field(
        ...,
        alias="list view options",
        description="the default list view options",
    )
    column_view_options: ColumnViewOptions = Field(
        ...,
        alias="column view options",
        description="the column view options for all windows",
    )
    folders_spring_open: bool = Field(
        ...,
        alias="folders spring open",
        description="Spring open folders after the specified delay?",
    )
    delay_before_springing: float = Field(
        ...,
        alias="delay before springing",
        description="the delay before springing open a container in seconds (from 0.167 to 1.169)",
    )
    desktop_shows_hard_disks: bool = Field(
        ...,
        alias="desktop shows hard disks",
        description="Hard disks appear on the desktop?",
    )
    desktop_shows_external_hard_disks: bool = Field(
        ...,
        alias="desktop shows external hard disks",
        description="External hard disks appear on the desktop?",
    )
    desktop_shows_removable_media: bool = Field(
        ...,
        alias="desktop shows removable media",
        description="CDs, DVDs, and iPods appear on the desktop?",
    )
    desktop_shows_connected_servers: bool = Field(
        ...,
        alias="desktop shows connected servers",
        description="Connected servers appear on the desktop?",
    )
    new_window_target: sdef_types.Specifier = Field(
        ...,
        alias="new window target",
        description="target location for a newly-opened Finder window",
    )
    folders_open_in_new_windows: bool = Field(
        ...,
        alias="folders open in new windows",
        description="Folders open into new windows?",
    )
    folders_open_in_new_tabs: bool = Field(
        ...,
        alias="folders open in new tabs",
        description="Folders open into new tabs?",
    )
    new_windows_open_in_column_view: bool = Field(
        ...,
        alias="new windows open in column view",
        description="Open new windows in column view?",
    )
    all_name_extensions_showing: bool = Field(
        ...,
        alias="all name extensions showing",
        description='Show name extensions, even for items whose "extension hidden" is true?',
    )


class Label(SDEFModel):
    """(NOT AVAILABLE YET) A Finder label (name and color)"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="label",
        code="clbl",
        description="(NOT AVAILABLE YET) A Finder label (name and color)",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="name",
                code="pnam",
                type="text",
                description="the name associated with the label",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="index",
                code="pidx",
                type="integer",
                description="the index in the front-to-back ordering within its container",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="color",
                code="colr",
                type="RGB color",
                description="the color associated with the label",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    name: str = Field(..., alias="name", description="the name associated with the label")
    index: int = Field(
        ...,
        alias="index",
        description="the index in the front-to-back ordering within its container",
    )
    color: sdef_types.Specifier = Field(
        ...,
        alias="color",
        description="the color associated with the label",
    )


class IconFamily(SDEFModel):
    """(NOT AVAILABLE YET) A family of icons"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="icon family",
        code="ifam",
        description="(NOT AVAILABLE YET) A family of icons",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="large monochrome icon and mask",
                code="ICN#",
                type="ICN#",
                description="the large black-and-white icon and the mask for large icons",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="large 8 bit mask",
                code="l8mk",
                type="l8mk",
                description="the large 8-bit mask for large 32-bit icons",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="large 32 bit icon",
                code="il32",
                type="il32",
                description="the large 32-bit color icon",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="large 8 bit icon",
                code="icl8",
                type="icl8",
                description="the large 8-bit color icon",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="large 4 bit icon",
                code="icl4",
                type="icl4",
                description="the large 4-bit color icon",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="small monochrome icon and mask",
                code="ics#",
                type="ics#",
                description="the small black-and-white icon and the mask for small icons",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="small 8 bit mask",
                code="ics8",
                type="s8mk",
                description="the small 8-bit mask for small 32-bit icons",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="small 32 bit icon",
                code="is32",
                type="is32",
                description="the small 32-bit color icon",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="small 8 bit icon",
                code="ics8",
                type="ics8",
                description="the small 8-bit color icon",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="small 4 bit icon",
                code="ics4",
                type="ics4",
                description="the small 4-bit color icon",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    large_monochrome_icon_and_mask: sdef_types.Specifier = Field(
        ...,
        alias="large monochrome icon and mask",
        description="the large black-and-white icon and the mask for large icons",
    )
    large_8_bit_mask: sdef_types.Specifier = Field(
        ...,
        alias="large 8 bit mask",
        description="the large 8-bit mask for large 32-bit icons",
    )
    large_32_bit_icon: sdef_types.Specifier = Field(
        ...,
        alias="large 32 bit icon",
        description="the large 32-bit color icon",
    )
    large_8_bit_icon: sdef_types.Specifier = Field(
        ...,
        alias="large 8 bit icon",
        description="the large 8-bit color icon",
    )
    large_4_bit_icon: sdef_types.Specifier = Field(
        ...,
        alias="large 4 bit icon",
        description="the large 4-bit color icon",
    )
    small_monochrome_icon_and_mask: sdef_types.Specifier = Field(
        ...,
        alias="small monochrome icon and mask",
        description="the small black-and-white icon and the mask for small icons",
    )
    small_8_bit_mask: sdef_types.Specifier = Field(
        ...,
        alias="small 8 bit mask",
        description="the small 8-bit mask for small 32-bit icons",
    )
    small_32_bit_icon: sdef_types.Specifier = Field(
        ...,
        alias="small 32 bit icon",
        description="the small 32-bit color icon",
    )
    small_8_bit_icon: sdef_types.Specifier = Field(
        ...,
        alias="small 8 bit icon",
        description="the small 8-bit color icon",
    )
    small_4_bit_icon: sdef_types.Specifier = Field(
        ...,
        alias="small 4 bit icon",
        description="the small 4-bit color icon",
    )


class IconViewOptions(SDEFModel):
    """the icon view options"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="icon view options",
        code="icop",
        description="the icon view options",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="arrangement",
                code="iarr",
                type="earr",
                description="the property by which to keep icons arranged",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="icon size",
                code="lvis",
                type="integer",
                description="the size of icons displayed in the icon view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="shows item info",
                code="mnfo",
                type="boolean",
                description="additional info about an item displayed in icon view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="shows icon preview",
                code="prvw",
                type="boolean",
                description="displays a preview of the item in icon view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="text size",
                code="fsiz",
                type="integer",
                description="the size of the text displayed in the icon view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="label position",
                code="lpos",
                type="epos",
                description="the location of the label in reference to the icon",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="background picture",
                code="ibkg",
                type="file",
                description="the background picture of the icon view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="background color",
                code="colr",
                type="RGB color",
                description="the background color of the icon view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    arrangement: Earr = Field(
        ...,
        alias="arrangement",
        description="the property by which to keep icons arranged",
    )
    icon_size: int = Field(
        ...,
        alias="icon size",
        description="the size of icons displayed in the icon view",
    )
    shows_item_info: bool = Field(
        ...,
        alias="shows item info",
        description="additional info about an item displayed in icon view",
    )
    shows_icon_preview: bool = Field(
        ...,
        alias="shows icon preview",
        description="displays a preview of the item in icon view",
    )
    text_size: int = Field(
        ...,
        alias="text size",
        description="the size of the text displayed in the icon view",
    )
    label_position: Epos = Field(
        ...,
        alias="label position",
        description="the location of the label in reference to the icon",
    )
    background_picture: sdef_types.File = Field(
        ...,
        alias="background picture",
        description="the background picture of the icon view",
    )
    background_color: sdef_types.Specifier = Field(
        ...,
        alias="background color",
        description="the background color of the icon view",
    )


class ColumnViewOptions(SDEFModel):
    """the column view options"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="column view options",
        code="cvop",
        description="the column view options",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="text size",
                code="fsiz",
                type="integer",
                description="the size of the text displayed in the column view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="shows icon",
                code="shic",
                type="boolean",
                description="displays an icon next to the label in column view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="shows icon preview",
                code="prvw",
                type="boolean",
                description="displays a preview of the item in column view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="shows preview column",
                code="shpr",
                type="boolean",
                description="displays the preview column in column view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="discloses preview pane",
                code="dspr",
                type="boolean",
                description="discloses the preview pane of the preview column in column view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    text_size: int = Field(
        ...,
        alias="text size",
        description="the size of the text displayed in the column view",
    )
    shows_icon: bool = Field(
        ...,
        alias="shows icon",
        description="displays an icon next to the label in column view",
    )
    shows_icon_preview: bool = Field(
        ...,
        alias="shows icon preview",
        description="displays a preview of the item in column view",
    )
    shows_preview_column: bool = Field(
        ...,
        alias="shows preview column",
        description="displays the preview column in column view",
    )
    discloses_preview_pane: bool = Field(
        ...,
        alias="discloses preview pane",
        description="discloses the preview pane of the preview column in column view",
    )


class ListViewOptions(SDEFModel):
    """the list view options"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="list view options",
        code="lvop",
        description="the list view options",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="calculates folder sizes",
                code="sfsz",
                type="boolean",
                description="Are folder sizes calculated and displayed in the window?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="shows icon preview",
                code="prvw",
                type="boolean",
                description="displays a preview of the item in list view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="icon size",
                code="lvis",
                type="lvic",
                description="the size of icons displayed in the list view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="text size",
                code="fsiz",
                type="integer",
                description="the size of the text displayed in the list view",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="sort column",
                code="srtc",
                type="column",
                description="the column that the list view is sorted on",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="uses relative dates",
                code="urdt",
                type="boolean",
                description="Are relative dates (e.g., today, yesterday) shown in the list view?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(type="column", description=None, hidden=None, access=None),
        ),
        responds_to=(),
    )
    calculates_folder_sizes: bool = Field(
        ...,
        alias="calculates folder sizes",
        description="Are folder sizes calculated and displayed in the window?",
    )
    shows_icon_preview: bool = Field(
        ...,
        alias="shows icon preview",
        description="displays a preview of the item in list view",
    )
    icon_size: Lvic = Field(
        ...,
        alias="icon size",
        description="the size of icons displayed in the list view",
    )
    text_size: int = Field(
        ...,
        alias="text size",
        description="the size of the text displayed in the list view",
    )
    sort_column: Column = Field(
        ...,
        alias="sort column",
        description="the column that the list view is sorted on",
    )
    uses_relative_dates: bool = Field(
        ...,
        alias="uses relative dates",
        description="Are relative dates (e.g., today, yesterday) shown in the list view?",
    )


class Column(SDEFModel):
    """a column of a list view"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="column",
        code="lvcl",
        description="a column of a list view",
        hidden=None,
        inherits=None,
        plural="columns",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="index",
                code="pidx",
                type="integer",
                description="the index in the front-to-back ordering within its container",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="name",
                code="pnam",
                type="elsv",
                description="the column name",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="sort direction",
                code="sord",
                type="sodr",
                description="The direction in which the window is sorted",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="width",
                code="clwd",
                type="integer",
                description="the width of this column",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="minimum width",
                code="clwn",
                type="integer",
                description="the minimum allowed width of this column",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="maximum width",
                code="clwm",
                type="integer",
                description="the maximum allowed width of this column",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="visible",
                code="pvis",
                type="boolean",
                description="is this column visible",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    index: int = Field(
        ...,
        alias="index",
        description="the index in the front-to-back ordering within its container",
    )
    name: Elsv = Field(..., alias="name", description="the column name")
    sort_direction: Sodr = Field(
        ...,
        alias="sort direction",
        description="The direction in which the window is sorted",
    )
    width: int = Field(..., alias="width", description="the width of this column")
    minimum_width: int = Field(
        ...,
        alias="minimum width",
        description="the minimum allowed width of this column",
    )
    maximum_width: int = Field(
        ...,
        alias="maximum width",
        description="the maximum allowed width of this column",
    )
    visible: bool = Field(..., alias="visible", description="is this column visible")


class AliasList(SDEFModel):
    """A list of aliases. Use 'as alias list' when a list of aliases is needed (instead of a list of file system item references)."""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="alias list",
        code="alst",
        description="A list of aliases. Use 'as alias list' when a list of aliases is needed (instead of a list of file system item references).",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(),
        elements=(),
        responds_to=(),
    )


class Earr(str, Enum):
    """Generated from SDEF."""

    NOT_ARRANGED = "narr"
    SNAP_TO_GRID = "grda"
    ARRANGED_BY_NAME = "nama"
    ARRANGED_BY_MODIFICATION_DATE = "mdta"
    ARRANGED_BY_CREATION_DATE = "cdta"
    ARRANGED_BY_SIZE = "siza"
    ARRANGED_BY_KIND = "kina"
    ARRANGED_BY_LABEL = "laba"


EARR_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="earr",
    code="earr",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="not arranged", code="narr", description=None),
        sdef_meta.EnumeratorMeta(name="snap to grid", code="grda", description=None),
        sdef_meta.EnumeratorMeta(name="arranged by name", code="nama", description=None),
        sdef_meta.EnumeratorMeta(
            name="arranged by modification date",
            code="mdta",
            description=None,
        ),
        sdef_meta.EnumeratorMeta(name="arranged by creation date", code="cdta", description=None),
        sdef_meta.EnumeratorMeta(name="arranged by size", code="siza", description=None),
        sdef_meta.EnumeratorMeta(name="arranged by kind", code="kina", description=None),
        sdef_meta.EnumeratorMeta(name="arranged by label", code="laba", description=None),
    ),
)


class Epos(str, Enum):
    """Generated from SDEF."""

    RIGHT = "lrgt"
    BOTTOM = "lbot"


EPOS_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="epos",
    code="epos",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="right", code="lrgt", description=None),
        sdef_meta.EnumeratorMeta(name="bottom", code="lbot", description=None),
    ),
)


class Sodr(str, Enum):
    """Generated from SDEF."""

    NORMAL = "snrm"
    REVERSED = "srvs"


SODR_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="sodr",
    code="sodr",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="normal", code="snrm", description=None),
        sdef_meta.EnumeratorMeta(name="reversed", code="srvs", description=None),
    ),
)


class Elsv(str, Enum):
    """Generated from SDEF."""

    NAME_COLUMN = "elsn"
    MODIFICATION_DATE_COLUMN = "elsm"
    CREATION_DATE_COLUMN = "elsc"
    SIZE_COLUMN = "elss"
    KIND_COLUMN = "elsk"
    LABEL_COLUMN = "elsl"
    VERSION_COLUMN = "elsv"
    COMMENT_COLUMN = "elsC"


ELSV_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="elsv",
    code="elsv",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="name column", code="elsn", description=None),
        sdef_meta.EnumeratorMeta(name="modification date column", code="elsm", description=None),
        sdef_meta.EnumeratorMeta(name="creation date column", code="elsc", description=None),
        sdef_meta.EnumeratorMeta(name="size column", code="elss", description=None),
        sdef_meta.EnumeratorMeta(name="kind column", code="elsk", description=None),
        sdef_meta.EnumeratorMeta(name="label column", code="elsl", description=None),
        sdef_meta.EnumeratorMeta(name="version column", code="elsv", description=None),
        sdef_meta.EnumeratorMeta(name="comment column", code="elsC", description=None),
    ),
)


class Lvic(str, Enum):
    """Generated from SDEF."""

    SMALL_ICON = "smic"
    LARGE_ICON = "lgic"


LVIC_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="lvic",
    code="lvic",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="small icon", code="smic", description=None),
        sdef_meta.EnumeratorMeta(name="large icon", code="lgic", description=None),
    ),
)


class TypeDefinitionsSuite:
    """Definitions of records used in scripting the Finder"""

    COMMANDS: ClassVar[tuple[type[SDEFCommand], ...]] = ()


__all__ = [
    "AliasList",
    "Column",
    "ColumnViewOptions",
    "Earr",
    "Elsv",
    "Epos",
    "IconFamily",
    "IconViewOptions",
    "Label",
    "ListViewOptions",
    "Lvic",
    "Preferences",
    "Sodr",
    "TypeDefinitionsSuite",
]
