from __future__ import annotations

# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from enum import Enum
from typing import Final

from openmac._internal.sdef import meta as sdef_meta


class Isiz(str, Enum):
    """Generated from SDEF."""

    MINI = "miic"
    SMALL = "smic"
    LARGE = "lgic"


ISIZ_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="isiz",
    code="isiz",
    description=None,
    hidden=True,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="mini", code="miic", description=None),
        sdef_meta.EnumeratorMeta(name="small", code="smic", description=None),
        sdef_meta.EnumeratorMeta(name="large", code="lgic", description=None),
    ),
)


class Sort(str, Enum):
    """Generated from SDEF."""

    NAME = "pnam"
    MODIFICATION_DATE = "asmo"
    CREATION_DATE = "ascd"
    SIZE = "phys"
    KIND = "kind"
    LABEL_INDEX = "labi"
    COMMENT = "comt"
    VERSION = "vers"


SORT_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="sort",
    code="sort",
    description=None,
    hidden=True,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="name", code="pnam", description=None),
        sdef_meta.EnumeratorMeta(name="modification date", code="asmo", description=None),
        sdef_meta.EnumeratorMeta(name="creation date", code="ascd", description=None),
        sdef_meta.EnumeratorMeta(name="size", code="phys", description=None),
        sdef_meta.EnumeratorMeta(name="kind", code="kind", description=None),
        sdef_meta.EnumeratorMeta(name="label index", code="labi", description=None),
        sdef_meta.EnumeratorMeta(name="comment", code="comt", description=None),
        sdef_meta.EnumeratorMeta(name="version", code="vers", description=None),
    ),
)
