from __future__ import annotations

# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import Final

from openmac._internal.sdef import meta as sdef_meta


class UnsignedInteger:
    """Generated from SDEF."""


UNSIGNED_INTEGER_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="unsigned integer",
    code="magn",
    description=None,
)


class DoubleInteger:
    """Generated from SDEF."""


DOUBLE_INTEGER_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="double integer",
    code="comp",
    description=None,
)


class RgbColor:
    """Generated from SDEF."""


RGB_COLOR_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="RGB color",
    code="cRGB",
    description=None,
)


class List:
    """Generated from SDEF."""


LIST_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="list",
    code="list",
    description=None,
)


class Property:
    """Generated from SDEF."""


PROPERTY_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="property",
    code="prop",
    description=None,
)


class Icn:
    """Generated from SDEF."""


ICN_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="ICN#",
    code="ICN#",
    description=None,
)


class Icl4:
    """Generated from SDEF."""


ICL4_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="icl4",
    code="icl4",
    description=None,
)


class Icl8:
    """Generated from SDEF."""


ICL8_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="icl8",
    code="icl8",
    description=None,
)


class Ics:
    """Generated from SDEF."""


ICS_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="ics#",
    code="ics#",
    description=None,
)


class Ics4:
    """Generated from SDEF."""


ICS4_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="ics4",
    code="ics4",
    description=None,
)


class Ics8:
    """Generated from SDEF."""


ICS8_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="ics8",
    code="ics8",
    description=None,
)


class Il32:
    """Generated from SDEF."""


IL32_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="il32",
    code="il32",
    description=None,
)


class Is32:
    """Generated from SDEF."""


IS32_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="is32",
    code="is32",
    description=None,
)


class L8mk:
    """Generated from SDEF."""


L8MK_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="l8mk",
    code="l8mk",
    description=None,
)


class S8mk:
    """Generated from SDEF."""


S8MK_VALUE_TYPE_META: Final[sdef_meta.ValueTypeMeta] = sdef_meta.ValueTypeMeta(
    name="s8mk",
    code="s8mk",
    description=None,
)
