from __future__ import annotations

# ruff: noqa: D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar

from pydantic import Field

import openmac._internal.sdef.types as sdef_types
from openmac._internal.sdef import meta as sdef_meta
from openmac._internal.sdef.base import SDEFClass
from openmac.finder.sdef.suites.finder_items.enumerations import Priv


class Item(SDEFClass):
    """An item"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="item",
        code="cobj",
        description="An item",
        hidden=None,
        inherits=None,
        plural="items",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="name",
                code="pnam",
                type="text",
                description="the name of the item",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="displayed name",
                code="dnam",
                type="text",
                description="the user-visible name of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="name extension",
                code="nmxt",
                type="text",
                description='the name extension of the item (such as "txt")',
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="extension hidden",
                code="hidx",
                type="boolean",
                description="Is the item's extension hidden from the user?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="index",
                code="pidx",
                type="integer",
                description="the index in the front-to-back ordering within its container",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="container",
                code="ctnr",
                type="specifier",
                description="the container of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="disk",
                code="cdis",
                type="specifier",
                description="the disk on which the item is stored",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="position",
                code="posn",
                type="point",
                description="the position of the item within its parent window (can only be set for an item in a window viewed as icons or buttons)",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="desktop position",
                code="dpos",
                type="point",
                description="the position of the item on the desktop",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="bounds",
                code="pbnd",
                type="rectangle",
                description="the bounding rectangle of the item (can only be set for an item in a window viewed as icons or buttons)",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="label index",
                code="labi",
                type="integer",
                description="the label of the item",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="locked",
                code="aslk",
                type="boolean",
                description="Is the file locked?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="kind",
                code="kind",
                type="text",
                description="the kind of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="description",
                code="dscr",
                type="text",
                description="a description of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="comment",
                code="comt",
                type="text",
                description='the comment of the item, displayed in the "Get Info" window',
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="size",
                code="ptsz",
                type="double integer",
                description="the logical size of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="physical size",
                code="phys",
                type="double integer",
                description="the actual space used by the item on disk",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="creation date",
                code="ascd",
                type="date",
                description="the date on which the item was created",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="modification date",
                code="asmo",
                type="date",
                description="the date on which the item was last modified",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="icon",
                code="iimg",
                type="icon family",
                description="the icon bitmap of the item",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="URL",
                code="pURL",
                type="text",
                description="the URL of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="owner",
                code="sown",
                type="text",
                description="the user that owns the container",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="group",
                code="sgrp",
                type="text",
                description="the user or group that has special access to the container",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="owner privileges",
                code="ownr",
                type="priv",
                description=None,
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="group privileges",
                code="gppr",
                type="priv",
                description=None,
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="everyones privileges",
                code="gstp",
                type="priv",
                description=None,
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="information window",
                code="iwnd",
                type="specifier",
                description="the information window for the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="properties",
                code="pALL",
                type="record",
                description="every property of an item",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="class",
                code="pcls",
                type="type",
                description="the class of the item",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    name: str = Field(..., alias="name", description="the name of the item")
    displayed_name: str = Field(
        ...,
        alias="displayed name",
        description="the user-visible name of the item",
    )
    name_extension: str = Field(
        ...,
        alias="name extension",
        description='the name extension of the item (such as "txt")',
    )
    extension_hidden: bool = Field(
        ...,
        alias="extension hidden",
        description="Is the item's extension hidden from the user?",
    )
    index: int = Field(
        ...,
        alias="index",
        description="the index in the front-to-back ordering within its container",
    )
    container: sdef_types.Specifier = Field(
        ...,
        alias="container",
        description="the container of the item",
    )
    disk: sdef_types.Specifier = Field(
        ...,
        alias="disk",
        description="the disk on which the item is stored",
    )
    position: sdef_types.Point = Field(
        ...,
        alias="position",
        description="the position of the item within its parent window (can only be set for an item in a window viewed as icons or buttons)",
    )
    desktop_position: sdef_types.Point = Field(
        ...,
        alias="desktop position",
        description="the position of the item on the desktop",
    )
    bounds: sdef_types.Rectangle = Field(
        ...,
        alias="bounds",
        description="the bounding rectangle of the item (can only be set for an item in a window viewed as icons or buttons)",
    )
    label_index: int = Field(..., alias="label index", description="the label of the item")
    locked: bool = Field(..., alias="locked", description="Is the file locked?")
    kind: str = Field(..., alias="kind", description="the kind of the item")
    description: str = Field(..., alias="description", description="a description of the item")
    comment: str = Field(
        ...,
        alias="comment",
        description='the comment of the item, displayed in the "Get Info" window',
    )
    size: int = Field(..., alias="size", description="the logical size of the item")
    physical_size: int = Field(
        ...,
        alias="physical size",
        description="the actual space used by the item on disk",
    )
    creation_date: sdef_types.Date = Field(
        ...,
        alias="creation date",
        description="the date on which the item was created",
    )
    modification_date: sdef_types.Date = Field(
        ...,
        alias="modification date",
        description="the date on which the item was last modified",
    )
    icon: sdef_types.Specifier = Field(..., alias="icon", description="the icon bitmap of the item")
    url: str = Field(..., alias="URL", description="the URL of the item")
    owner: str = Field(..., alias="owner", description="the user that owns the container")
    group: str = Field(
        ...,
        alias="group",
        description="the user or group that has special access to the container",
    )
    owner_privileges: Priv = Field(..., alias="owner privileges", description=None)
    group_privileges: Priv = Field(..., alias="group privileges", description=None)
    everyones_privileges: Priv = Field(..., alias="everyones privileges", description=None)
    information_window: sdef_types.Specifier = Field(
        ...,
        alias="information window",
        description="the information window for the item",
    )
    properties: sdef_types.Record = Field(
        ...,
        alias="properties",
        description="every property of an item",
    )
    class_: str = Field(..., alias="class", description="the class of the item")
