from __future__ import annotations

import importlib

# ruff: noqa: D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import TYPE_CHECKING, ClassVar

from pydantic import Field

import openmac._internal.sdef.types as sdef_types
from openmac._internal.sdef import meta as sdef_meta
from openmac._internal.sdef.base import SDEFClass

if TYPE_CHECKING:
    from openmac.apps.finder.sdef.suites.type_definitions.classes import (
        ColumnViewOptions as TypeDefinitionsColumnViewOptionsType,
        IconViewOptions as TypeDefinitionsIconViewOptionsType,
        ListViewOptions as TypeDefinitionsListViewOptionsType,
    )
from openmac.apps.finder.sdef.suites.window_classes.enumerations import (
    Ecvw,
    Ipnl,
    Pple,
)


class Window(SDEFClass):
    """A window"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="window",
        code="cwin",
        description="A window",
        hidden=None,
        inherits=None,
        plural="windows",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="id",
                code="ID  ",
                type="integer",
                description="the unique id for this window",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="position",
                code="posn",
                type="point",
                description="the upper left position of the window",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="bounds",
                code="pbnd",
                type="rectangle",
                description="the boundary rectangle for the window",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="titled",
                code="ptit",
                type="boolean",
                description="Does the window have a title bar?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="name",
                code="pnam",
                type="text",
                description="the name of the window",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="index",
                code="pidx",
                type="integer",
                description="the number of the window in the front-to-back layer ordering",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="closeable",
                code="hclb",
                type="boolean",
                description="Does the window have a close box?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="floating",
                code="isfl",
                type="boolean",
                description="Does the window have a title bar?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="modal",
                code="pmod",
                type="boolean",
                description="Is the window modal?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="resizable",
                code="prsz",
                type="boolean",
                description="Is the window resizable?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="zoomable",
                code="iszm",
                type="boolean",
                description="Is the window zoomable?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="zoomed",
                code="pzum",
                type="boolean",
                description="Is the window zoomed?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="visible",
                code="pvis",
                type="boolean",
                description="Is the window visible (always true for open Finder windows)?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="collapsed",
                code="wshd",
                type="boolean",
                description="Is the window collapsed",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="properties",
                code="pALL",
                type="record",
                description="every property of a window",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    id_: int = Field(..., alias="id", description="the unique id for this window")
    position: sdef_types.Point = Field(
        ...,
        alias="position",
        description="the upper left position of the window",
    )
    bounds: sdef_types.Rectangle = Field(
        ...,
        alias="bounds",
        description="the boundary rectangle for the window",
    )
    titled: bool = Field(..., alias="titled", description="Does the window have a title bar?")
    name: str = Field(..., alias="name", description="the name of the window")
    index: int = Field(
        ...,
        alias="index",
        description="the number of the window in the front-to-back layer ordering",
    )
    closeable: bool = Field(..., alias="closeable", description="Does the window have a close box?")
    floating: bool = Field(..., alias="floating", description="Does the window have a title bar?")
    modal: bool = Field(..., alias="modal", description="Is the window modal?")
    resizable: bool = Field(..., alias="resizable", description="Is the window resizable?")
    zoomable: bool = Field(..., alias="zoomable", description="Is the window zoomable?")
    zoomed: bool = Field(..., alias="zoomed", description="Is the window zoomed?")
    visible: bool = Field(
        ...,
        alias="visible",
        description="Is the window visible (always true for open Finder windows)?",
    )
    collapsed: bool = Field(..., alias="collapsed", description="Is the window collapsed")
    properties: sdef_types.Record = Field(
        ...,
        alias="properties",
        description="every property of a window",
    )


class FinderWindow(Window):
    """A file viewer window"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="Finder window",
        code="brow",
        description="A file viewer window",
        hidden=None,
        inherits="window",
        plural="Finder windows",
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="target",
                code="fvtg",
                type="specifier",
                description="the container at which this file viewer is targeted",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="current view",
                code="pvew",
                type="ecvw",
                description="the current view for the container window",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="icon view options",
                code="icop",
                type="icon view options",
                description="the icon view options for the container window",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="list view options",
                code="lvop",
                type="list view options",
                description="the list view options for the container window",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="column view options",
                code="cvop",
                type="column view options",
                description="the column view options for the container window",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="toolbar visible",
                code="tbvi",
                type="boolean",
                description="Is the window's toolbar visible?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="statusbar visible",
                code="stvi",
                type="boolean",
                description="Is the window's status bar visible?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="pathbar visible",
                code="pbvi",
                type="boolean",
                description="Is the window's path bar visible?",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="sidebar width",
                code="sbwi",
                type="integer",
                description="the width of the sidebar for the container window",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    target: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        alias="target",
        description="the container at which this file viewer is targeted",
    )
    current_view: Ecvw = Field(
        ...,
        alias="current view",
        description="the current view for the container window",
    )
    icon_view_options: sdef_types.Specifier[TypeDefinitionsIconViewOptionsType] = Field(
        ...,
        alias="icon view options",
        description="the icon view options for the container window",
    )
    list_view_options: sdef_types.Specifier[TypeDefinitionsListViewOptionsType] = Field(
        ...,
        alias="list view options",
        description="the list view options for the container window",
    )
    column_view_options: sdef_types.Specifier[TypeDefinitionsColumnViewOptionsType] = Field(
        ...,
        alias="column view options",
        description="the column view options for the container window",
    )
    toolbar_visible: bool = Field(
        ...,
        alias="toolbar visible",
        description="Is the window's toolbar visible?",
    )
    statusbar_visible: bool = Field(
        ...,
        alias="statusbar visible",
        description="Is the window's status bar visible?",
    )
    pathbar_visible: bool = Field(
        ...,
        alias="pathbar visible",
        description="Is the window's path bar visible?",
    )
    sidebar_width: int = Field(
        ...,
        alias="sidebar width",
        description="the width of the sidebar for the container window",
    )


class DesktopWindow(FinderWindow):
    """the desktop window"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="desktop window",
        code="dktw",
        description="the desktop window",
        hidden=None,
        inherits="Finder window",
        plural=None,
        id=None,
        properties=(),
        elements=(),
        responds_to=(),
    )


class InformationWindow(Window):
    """An inspector window (opened by "Show Info")"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="information window",
        code="iwnd",
        description='An inspector window (opened by "Show Info")',
        hidden=None,
        inherits="window",
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="item",
                code="cobj",
                type="specifier",
                description="the item from which this window was opened",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="current panel",
                code="panl",
                type="ipnl",
                description="the current panel in the information window",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    item: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        alias="item",
        description="the item from which this window was opened",
    )
    current_panel: Ipnl = Field(
        ...,
        alias="current panel",
        description="the current panel in the information window",
    )


class PreferencesWindow(Window):
    """The Finder Preferences window"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="preferences window",
        code="pwnd",
        description="The Finder Preferences window",
        hidden=None,
        inherits="window",
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="current panel",
                code="panl",
                type="pple",
                description="The current panel in the Finder preferences window",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    current_panel: Pple = Field(
        ...,
        alias="current panel",
        description="The current panel in the Finder preferences window",
    )


class ClippingWindow(Window):
    """The window containing a clipping"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="clipping window",
        code="lwnd",
        description="The window containing a clipping",
        hidden=None,
        inherits="window",
        plural="clipping windows",
        id=None,
        properties=(),
        elements=(),
        responds_to=(),
    )


_CROSS_SUITE_TYPES_NAMESPACE = {
    "TypeDefinitionsColumnViewOptionsType": importlib.import_module(
        "openmac.apps.finder.sdef.suites.type_definitions.classes",
    ).ColumnViewOptions,
    "TypeDefinitionsIconViewOptionsType": importlib.import_module(
        "openmac.apps.finder.sdef.suites.type_definitions.classes",
    ).IconViewOptions,
    "TypeDefinitionsListViewOptionsType": importlib.import_module(
        "openmac.apps.finder.sdef.suites.type_definitions.classes",
    ).ListViewOptions,
}

Window.model_rebuild(_types_namespace=_CROSS_SUITE_TYPES_NAMESPACE)
FinderWindow.model_rebuild(_types_namespace=_CROSS_SUITE_TYPES_NAMESPACE)
DesktopWindow.model_rebuild(_types_namespace=_CROSS_SUITE_TYPES_NAMESPACE)
InformationWindow.model_rebuild(_types_namespace=_CROSS_SUITE_TYPES_NAMESPACE)
PreferencesWindow.model_rebuild(_types_namespace=_CROSS_SUITE_TYPES_NAMESPACE)
ClippingWindow.model_rebuild(_types_namespace=_CROSS_SUITE_TYPES_NAMESPACE)
