from __future__ import annotations

# ruff: noqa: PIE796
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from enum import Enum
from typing import Final

from openmac._internal.sdef import meta as sdef_meta


class Ipnl(str, Enum):
    """Generated from SDEF."""

    GENERAL_INFORMATION_PANEL = "gpnl"
    SHARING_PANEL = "spnl"
    MEMORY_PANEL = "mpnl"
    PREVIEW_PANEL = "vpnl"
    APPLICATION_PANEL = "apnl"
    LANGUAGES_PANEL = "pklg"
    PLUGINS_PANEL = "pkpg"
    NAME_EXTENSION_PANEL = "npnl"
    COMMENTS_PANEL = "cpnl"
    CONTENT_INDEX_PANEL = "cinl"
    BURNING_PANEL = "bpnl"
    MORE_INFO_PANEL = "minl"
    SIMPLE_HEADER_PANEL = "shnl"


IPNL_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="ipnl",
    code="ipnl",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="General Information panel", code="gpnl", description=None),
        sdef_meta.EnumeratorMeta(name="Sharing panel", code="spnl", description=None),
        sdef_meta.EnumeratorMeta(name="Memory panel", code="mpnl", description=None),
        sdef_meta.EnumeratorMeta(name="Preview panel", code="vpnl", description=None),
        sdef_meta.EnumeratorMeta(name="Application panel", code="apnl", description=None),
        sdef_meta.EnumeratorMeta(name="Languages panel", code="pklg", description=None),
        sdef_meta.EnumeratorMeta(name="Plugins panel", code="pkpg", description=None),
        sdef_meta.EnumeratorMeta(name="Name & Extension panel", code="npnl", description=None),
        sdef_meta.EnumeratorMeta(name="Comments panel", code="cpnl", description=None),
        sdef_meta.EnumeratorMeta(name="Content Index panel", code="cinl", description=None),
        sdef_meta.EnumeratorMeta(name="Burning panel", code="bpnl", description=None),
        sdef_meta.EnumeratorMeta(name="More Info panel", code="minl", description=None),
        sdef_meta.EnumeratorMeta(name="Simple Header panel", code="shnl", description=None),
    ),
)


class Pple(str, Enum):
    """Generated from SDEF."""

    GENERAL_PREFERENCES_PANEL = "pgnp"
    LABEL_PREFERENCES_PANEL = "plbp"
    SIDEBAR_PREFERENCES_PANEL = "psid"
    ADVANCED_PREFERENCES_PANEL = "padv"


PPLE_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="pple",
    code="pple",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="General Preferences panel", code="pgnp", description=None),
        sdef_meta.EnumeratorMeta(name="Label Preferences panel", code="plbp", description=None),
        sdef_meta.EnumeratorMeta(name="Sidebar Preferences panel", code="psid", description=None),
        sdef_meta.EnumeratorMeta(name="Advanced Preferences panel", code="padv", description=None),
    ),
)


class Ecvw(str, Enum):
    """Generated from SDEF."""

    ICON_VIEW = "icnv"
    LIST_VIEW = "lsvw"
    COLUMN_VIEW = "clvw"
    GROUP_VIEW = "flvw"
    FLOW_VIEW = "flvw"


ECVW_ENUMERATION_META: Final[sdef_meta.EnumerationMeta] = sdef_meta.EnumerationMeta(
    name="ecvw",
    code="ecvw",
    description=None,
    hidden=None,
    enumerators=(
        sdef_meta.EnumeratorMeta(name="icon view", code="icnv", description=None),
        sdef_meta.EnumeratorMeta(name="list view", code="lsvw", description=None),
        sdef_meta.EnumeratorMeta(name="column view", code="clvw", description=None),
        sdef_meta.EnumeratorMeta(name="group view", code="flvw", description=None),
        sdef_meta.EnumeratorMeta(name="flow view", code="flvw", description=None),
    ),
)
