from __future__ import annotations

# ruff: noqa: D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar

from pydantic import Field

import openmac._internal.sdef.types as sdef_types
import openmac.apps.finder.sdef.suites.finder_basics.classes as finder_basics_classes_module
from openmac._internal.sdef import meta as sdef_meta


class Application(finder_basics_classes_module.Application):
    """The Finder"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="application",
        code=None,
        description="The Finder",
        hidden=None,
        inherits="application",
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="desktop picture",
                code="dpic",
                type="file",
                description="the desktop picture of the main monitor",
                hidden=None,
                access=None,
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    desktop_picture: sdef_types.File = Field(
        ...,
        alias="desktop picture",
        description="the desktop picture of the main monitor",
    )
