from __future__ import annotations

# ruff: noqa: D301, D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar

from pydantic import Field

from openmac._internal.sdef import meta as sdef_meta
from openmac._internal.sdef.base import SDEFClass


class Tab(SDEFClass):
    """A tab.\n\nSDEF extras: {"cocoas": [{"class": "TabAppleScript"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="tab",
        code="CrTb",
        description="A tab.",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="id",
                code="ID  ",
                type="text",
                description="Unique ID of the tab.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="title",
                code="pnam",
                type="text",
                description="The title of the tab.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="URL",
                code="URL ",
                type="text",
                description="The url visible to the user.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="loading",
                code="ldng",
                type="boolean",
                description="Is loading?",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(
            (
                "undo",
                None,
            ),
            (
                "redo",
                None,
            ),
            (
                "cut selection",
                None,
            ),
            (
                "copy selection",
                None,
            ),
            (
                "paste selection",
                None,
            ),
            (
                "select all",
                None,
            ),
            (
                "go back",
                None,
            ),
            (
                "go forward",
                None,
            ),
            (
                "reload",
                None,
            ),
            (
                "stop",
                None,
            ),
            (
                "print",
                None,
            ),
            (
                "view source",
                None,
            ),
            (
                "save",
                None,
            ),
            (
                "close",
                None,
            ),
            (
                "execute",
                None,
            ),
        ),
    )
    id_: str = Field(
        ...,
        alias="id",
        description="Unique ID of the tab.",
        json_schema_extra={"cocoas": [{"key": "uniqueID"}]},
    )
    title: str = Field(..., alias="title", description="The title of the tab.")
    url: str = Field(..., alias="URL", description="The url visible to the user.")
    loading: bool = Field(..., alias="loading", description="Is loading?")


class BookmarkFolder(SDEFClass):
    """A bookmarks folder that contains other bookmarks folder and bookmark items.\n\nSDEF extras: {"cocoas": [{"class": "BookmarkFolderAppleScript"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="bookmark folder",
        code="CrBF",
        description="A bookmarks folder that contains other bookmarks folder and bookmark items.",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="id",
                code="ID  ",
                type="text",
                description="Unique ID of the bookmark folder.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="title",
                code="pnam",
                type="text",
                description="The title of the folder.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="index",
                code="pidx",
                type="number",
                description="Returns the index with respect to its parent bookmark folder.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(
                type="bookmark folder",
                description="The bookmark folders present within.",
                hidden=None,
                access=None,
            ),
            sdef_meta.ElementMeta(
                type="bookmark item",
                description="The bookmarks present within.",
                hidden=None,
                access=None,
            ),
        ),
        responds_to=(),
    )
    id_: str = Field(
        ...,
        alias="id",
        description="Unique ID of the bookmark folder.",
        json_schema_extra={"cocoas": [{"key": "uniqueID"}]},
    )
    title: str = Field(..., alias="title", description="The title of the folder.")
    index: float = Field(
        ...,
        alias="index",
        description="Returns the index with respect to its parent bookmark folder.",
        json_schema_extra={"cocoas": [{"key": "index"}]},
    )


class BookmarkItem(SDEFClass):
    """An item consists of an URL and the title of a bookmark\n\nSDEF extras: {"cocoas": [{"class": "BookmarkItemAppleScript"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="bookmark item",
        code="CrBI",
        description="An item consists of an URL and the title of a bookmark",
        hidden=None,
        inherits=None,
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="id",
                code="ID  ",
                type="text",
                description="Unique ID of the bookmark item.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="title",
                code="pnam",
                type="text",
                description="The title of the bookmark item.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="URL",
                code="URL ",
                type="text",
                description="The URL of the bookmark.",
                hidden=None,
                access=None,
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="index",
                code="pidx",
                type="number",
                description="Returns the index with respect to its parent bookmark folder.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(),
        responds_to=(),
    )
    id_: str = Field(
        ...,
        alias="id",
        description="Unique ID of the bookmark item.",
        json_schema_extra={"cocoas": [{"key": "uniqueID"}]},
    )
    title: str = Field(..., alias="title", description="The title of the bookmark item.")
    url: str = Field(..., alias="URL", description="The URL of the bookmark.")
    index: float = Field(
        ...,
        alias="index",
        description="Returns the index with respect to its parent bookmark folder.",
        json_schema_extra={"cocoas": [{"key": "index"}]},
    )
