from __future__ import annotations

# ruff: noqa: D301, D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import ClassVar

from pydantic import Field

import openmac.chrome.sdef.suites.standard.classes as standard_classes_module
from openmac._internal.sdef import meta as sdef_meta
from openmac.chrome.sdef.suites.chromium.classes import BookmarkFolder


class Application(standard_classes_module.Application):
    """The application\'s top-level scripting object.\n\nSDEF extras: {"cocoas": [{"class": "BrowserCrApplication"}]}"""

    SDEF_META: ClassVar[sdef_meta.ClassMeta] = sdef_meta.ClassMeta(
        name="application",
        code=None,
        description="The application's top-level scripting object.",
        hidden=None,
        inherits="application",
        plural=None,
        id=None,
        properties=(
            sdef_meta.PropertyMeta(
                name="bookmarks bar",
                code="ChBB",
                type="bookmark folder",
                description="The bookmarks bar bookmark folder.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
            sdef_meta.PropertyMeta(
                name="other bookmarks",
                code="ChOB",
                type="bookmark folder",
                description="The other bookmarks bookmark folder.",
                hidden=None,
                access="r",
                in_properties=None,
            ),
        ),
        elements=(
            sdef_meta.ElementMeta(
                type="bookmark folder",
                description="Contains the bookmarks bar and other bookmarks folder.",
                hidden=None,
                access="r",
            ),
        ),
        responds_to=(),
    )
    bookmarks_bar: BookmarkFolder = Field(
        ...,
        alias="bookmarks bar",
        description="The bookmarks bar bookmark folder.",
        json_schema_extra={"cocoas": [{"key": "bookmarksBar"}]},
    )
    other_bookmarks: BookmarkFolder = Field(
        ...,
        alias="other bookmarks",
        description="The other bookmarks bookmark folder.",
        json_schema_extra={"cocoas": [{"key": "otherBookmarks"}]},
    )
