from __future__ import annotations

from types import NoneType

# mypy: disable-error-code=valid-type
# ruff: noqa: D301, D400, D415
# Generated by tools/sdef/generate_openmac_suites.py. Do not edit manually.
from typing import Any, ClassVar

from pydantic import Field

import openmac._internal.sdef.types as sdef_types
from openmac._internal.sdef import meta as sdef_meta
from openmac._internal.sdef.base import SDEFClass, SDEFCommand


class ReloadCommand(SDEFCommand[NoneType]):
    """Reload a tab.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="reload",
        code="CrSuRlod",
        description="Reload a tab.",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(),
        result=None,
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )


class GoBackCommand(SDEFCommand[NoneType]):
    """Go Back (If Possible).\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="go back",
        code="CrSuBack",
        description="Go Back (If Possible).",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(),
        result=None,
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )


class GoForwardCommand(SDEFCommand[NoneType]):
    """Go Forward (If Possible).\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="go forward",
        code="CrSuFwd ",
        description="Go Forward (If Possible).",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(),
        result=None,
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )


class SelectAllCommand(SDEFCommand[NoneType]):
    """Select all.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="select all",
        code="CrSuSlAl",
        description="Select all.",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(),
        result=None,
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )


class CutSelectionCommand(SDEFCommand[NoneType]):
    """Cut selected text (If Possible).\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="cut selection",
        code="CrSuCut ",
        description="Cut selected text (If Possible).",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(),
        result=None,
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )


class CopySelectionCommand(SDEFCommand[NoneType]):
    """Copy text.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="copy selection",
        code="CrSuCop ",
        description="Copy text.",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(),
        result=None,
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )


class PasteSelectionCommand(SDEFCommand[NoneType]):
    """Paste text (If Possible).\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="paste selection",
        code="CrSuPast",
        description="Paste text (If Possible).",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(),
        result=None,
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )


class UndoCommand(SDEFCommand[NoneType]):
    """Undo the last change.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="undo",
        code="CrSuUndo",
        description="Undo the last change.",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(),
        result=None,
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )


class RedoCommand(SDEFCommand[NoneType]):
    """Redo the last change.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="redo",
        code="CrSuRedo",
        description="Redo the last change.",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(),
        result=None,
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )


class StopCommand(SDEFCommand[NoneType]):
    """Stop the current tab from loading.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="stop",
        code="CrSustop",
        description="Stop the current tab from loading.",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(),
        result=None,
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )


class ViewSourceCommand(SDEFCommand[NoneType]):
    """View the HTML source of the tab.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}]}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="view source",
        code="CrSuVSrc",
        description="View the HTML source of the tab.",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(),
        result=None,
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )


class ExecuteCommand(SDEFCommand[Any]):
    """Execute a piece of javascript.\n\nSDEF extras: {"direct_parameters": [{"access_group": [], "description": "The tab to execute the command in.", "type": "specifier", "type_element": []}], "parameters": [{"cocoa": [{"key": "javascript"}], "code": "JvSc", "description": "The javascript code to execute.", "name": "javascript", "type": "text", "type_element": []}], "result": {"type": "any", "type_element": []}}"""

    SDEF_META: ClassVar[sdef_meta.CommandMeta] = sdef_meta.CommandMeta(
        name="execute",
        code="CrSuExJa",
        description="Execute a piece of javascript.",
        hidden=None,
        bundle_id="com.google.Chrome",
        direct_parameter_type="specifier",
        has_direct_parameter=True,
        direct_parameter_optional=None,
        parameters=(
            sdef_meta.ParameterMeta(
                name="javascript",
                code="JvSc",
                type="text",
                description="The javascript code to execute.",
                optional=None,
                hidden=None,
                requires_access=None,
                field_name="javascript",
            ),
        ),
        result=sdef_meta.ResultMeta(type="any", description=None, optional=None),
        access_groups=(),
    )
    direct_parameter: sdef_types.Specifier[SDEFClass] = Field(
        ...,
        description="The tab to execute the command in.",
    )
    javascript: str = Field(
        ...,
        alias="javascript",
        description="The javascript code to execute.",
        json_schema_extra={"cocoas": [{"key": "javascript"}]},
    )
